# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/qsi.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QSi_Window(object):
    def setupUi(self, QSi_Window):
        QSi_Window.setObjectName(_fromUtf8("QSi_Window"))
        QSi_Window.resize(938, 677)
        self.centralwidget = QtGui.QWidget(QSi_Window)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.splitter_data = QtGui.QSplitter(self.centralwidget)
        self.splitter_data.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_data.setObjectName(_fromUtf8("splitter_data"))
        self.layoutWidget = QtGui.QWidget(self.splitter_data)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(180, 60))
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.rb_distri = QtGui.QRadioButton(self.groupBox)
        self.rb_distri.setEnabled(True)
        self.rb_distri.setGeometry(QtCore.QRect(0, 20, 163, 22))
        self.rb_distri.setChecked(True)
        self.rb_distri.setObjectName(_fromUtf8("rb_distri"))
        self.rb_simu = QtGui.QRadioButton(self.groupBox)
        self.rb_simu.setGeometry(QtCore.QRect(0, 40, 163, 22))
        self.rb_simu.setObjectName(_fromUtf8("rb_simu"))
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.cb_Xaxis = QtGui.QComboBox(self.layoutWidget)
        self.cb_Xaxis.setObjectName(_fromUtf8("cb_Xaxis"))
        self.horizontalLayout_4.addWidget(self.cb_Xaxis)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.cb_Yaxis = QtGui.QComboBox(self.layoutWidget)
        self.cb_Yaxis.setObjectName(_fromUtf8("cb_Yaxis"))
        self.horizontalLayout_5.addWidget(self.cb_Yaxis)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_2.addWidget(self.label_8)
        self.sb_NPoints = QtGui.QSpinBox(self.layoutWidget)
        self.sb_NPoints.setMinimum(10)
        self.sb_NPoints.setMaximum(500)
        self.sb_NPoints.setProperty("value", 50)
        self.sb_NPoints.setObjectName(_fromUtf8("sb_NPoints"))
        self.horizontalLayout_2.addWidget(self.sb_NPoints)
        self.cbPlotErrors = QtGui.QCheckBox(self.layoutWidget)
        self.cbPlotErrors.setEnabled(True)
        self.cbPlotErrors.setObjectName(_fromUtf8("cbPlotErrors"))
        self.horizontalLayout_2.addWidget(self.cbPlotErrors)
        self.sbError = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.sbError.setEnabled(True)
        self.sbError.setMaximum(100.0)
        self.sbError.setProperty("value", 95.0)
        self.sbError.setObjectName(_fromUtf8("sbError"))
        self.horizontalLayout_2.addWidget(self.sbError)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.splitter = QtGui.QSplitter(self.layoutWidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.stackedWidget = QtGui.QStackedWidget(self.splitter)
        self.stackedWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_simu = QtGui.QWidget()
        self.page_simu.setObjectName(_fromUtf8("page_simu"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.page_simu)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.table_species = QtGui.QTableWidget(self.page_simu)
        self.table_species.setObjectName(_fromUtf8("table_species"))
        self.table_species.setColumnCount(4)
        self.table_species.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.table_species.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_species.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_species.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_species.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_species.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_species.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_species.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.table_species.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.table_species.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.table_species.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.table_species.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.table_species.setItem(1, 2, item)
        self.table_species.verticalHeader().setVisible(False)
        self.table_species.verticalHeader().setCascadingSectionResizes(True)
        self.horizontalLayout_3.addWidget(self.table_species)
        self.stackedWidget.addWidget(self.page_simu)
        self.page_titr = QtGui.QWidget()
        self.page_titr.setObjectName(_fromUtf8("page_titr"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page_titr)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.table_titration = QtGui.QTableWidget(self.page_titr)
        self.table_titration.setObjectName(_fromUtf8("table_titration"))
        self.table_titration.setColumnCount(3)
        self.table_titration.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.table_titration.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_titration.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_titration.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_titration.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_titration.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_titration.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.table_titration.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.table_titration.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.table_titration.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.table_titration.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.table_titration.setItem(1, 2, item)
        self.table_titration.verticalHeader().setVisible(False)
        self.table_titration.verticalHeader().setCascadingSectionResizes(True)
        self.verticalLayout_5.addWidget(self.table_titration)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(self.page_titr)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.page_titr)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.page_titr)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.dsb_V0 = QtGui.QDoubleSpinBox(self.page_titr)
        self.dsb_V0.setProperty("value", 10.0)
        self.dsb_V0.setObjectName(_fromUtf8("dsb_V0"))
        self.gridLayout.addWidget(self.dsb_V0, 1, 1, 1, 1)
        self.dsb_Vf = QtGui.QDoubleSpinBox(self.page_titr)
        self.dsb_Vf.setProperty("value", 11.0)
        self.dsb_Vf.setObjectName(_fromUtf8("dsb_Vf"))
        self.gridLayout.addWidget(self.dsb_Vf, 1, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.stackedWidget.addWidget(self.page_titr)
        self.table_model = QtGui.QTableWidget(self.splitter)
        self.table_model.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.table_model.setCornerButtonEnabled(False)
        self.table_model.setObjectName(_fromUtf8("table_model"))
        self.table_model.setColumnCount(3)
        self.table_model.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.table_model.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_model.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_model.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_model.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_model.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_model.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.table_model.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.table_model.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.table_model.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.table_model.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.table_model.setItem(1, 2, item)
        self.table_model.verticalHeader().setVisible(False)
        self.table_model.verticalHeader().setCascadingSectionResizes(True)
        self.table_model.verticalHeader().setHighlightSections(True)
        self.verticalLayout_3.addWidget(self.splitter)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pb_addbeta = QtGui.QPushButton(self.layoutWidget)
        self.pb_addbeta.setObjectName(_fromUtf8("pb_addbeta"))
        self.horizontalLayout.addWidget(self.pb_addbeta)
        self.pb_removebeta = QtGui.QPushButton(self.layoutWidget)
        self.pb_removebeta.setObjectName(_fromUtf8("pb_removebeta"))
        self.horizontalLayout.addWidget(self.pb_removebeta)
        self.pb_addreag = QtGui.QPushButton(self.layoutWidget)
        self.pb_addreag.setObjectName(_fromUtf8("pb_addreag"))
        self.horizontalLayout.addWidget(self.pb_addreag)
        self.pb_removereag = QtGui.QPushButton(self.layoutWidget)
        self.pb_removereag.setObjectName(_fromUtf8("pb_removereag"))
        self.horizontalLayout.addWidget(self.pb_removereag)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.pb_go = QtGui.QPushButton(self.layoutWidget)
        self.pb_go.setObjectName(_fromUtf8("pb_go"))
        self.horizontalLayout_6.addWidget(self.pb_go)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.layoutWidget1 = QtGui.QWidget(self.splitter_data)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.widget_plot = QtGui.QWidget(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_plot.sizePolicy().hasHeightForWidth())
        self.widget_plot.setSizePolicy(sizePolicy)
        self.widget_plot.setSizeIncrement(QtCore.QSize(1, 1))
        self.widget_plot.setObjectName(_fromUtf8("widget_plot"))
        self.verticalLayout_4.addWidget(self.widget_plot)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.dsb_ignorelowerthan = QtGui.QDoubleSpinBox(self.layoutWidget1)
        self.dsb_ignorelowerthan.setObjectName(_fromUtf8("dsb_ignorelowerthan"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.dsb_ignorelowerthan)
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.dsb_unlabellowerthan = QtGui.QDoubleSpinBox(self.layoutWidget1)
        self.dsb_unlabellowerthan.setObjectName(_fromUtf8("dsb_unlabellowerthan"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.dsb_unlabellowerthan)
        self.verticalLayout_4.addLayout(self.formLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_8.addWidget(self.splitter_data)
        QSi_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(QSi_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 938, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuPlot = QtGui.QMenu(self.menubar)
        self.menuPlot.setEnabled(False)
        self.menuPlot.setObjectName(_fromUtf8("menuPlot"))
        QSi_Window.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(QSi_Window)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        QSi_Window.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(QSi_Window)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(QSi_Window)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(QSi_Window)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_as = QtGui.QAction(QSi_Window)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionExit = QtGui.QAction(QSi_Window)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionPlot_unplot = QtGui.QAction(QSi_Window)
        self.actionPlot_unplot.setEnabled(False)
        self.actionPlot_unplot.setObjectName(_fromUtf8("actionPlot_unplot"))
        self.actionAddittional_data = QtGui.QAction(QSi_Window)
        self.actionAddittional_data.setObjectName(_fromUtf8("actionAddittional_data"))
        self.actionExport_Graph = QtGui.QAction(QSi_Window)
        self.actionExport_Graph.setObjectName(_fromUtf8("actionExport_Graph"))
        self.actionExport_Data = QtGui.QAction(QSi_Window)
        self.actionExport_Data.setObjectName(_fromUtf8("actionExport_Data"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_Graph)
        self.menuFile.addAction(self.actionExport_Data)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuPlot.addAction(self.actionPlot_unplot)
        self.menuPlot.addAction(self.actionAddittional_data)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPlot.menuAction())

        self.retranslateUi(QSi_Window)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("activated()")), QSi_Window.close)
        QtCore.QMetaObject.connectSlotsByName(QSi_Window)

    def retranslateUi(self, QSi_Window):
        QSi_Window.setWindowTitle(_translate("QSi_Window", "MainWindow", None))
        self.groupBox.setTitle(_translate("QSi_Window", "Type of  Graphic", None))
        self.rb_distri.setText(_translate("QSi_Window", "Species Distribution", None))
        self.rb_simu.setText(_translate("QSi_Window", "Titration Simulation", None))
        self.label.setText(_translate("QSi_Window", "X-axis", None))
        self.label_2.setText(_translate("QSi_Window", "Y-axis", None))
        self.label_8.setText(_translate("QSi_Window", "Points", None))
        self.cbPlotErrors.setText(_translate("QSi_Window", "plot errors at", None))
        self.sbError.setSuffix(_translate("QSi_Window", "%", None))
        item = self.table_species.verticalHeaderItem(0)
        item.setText(_translate("QSi_Window", "1", None))
        item = self.table_species.verticalHeaderItem(1)
        item.setText(_translate("QSi_Window", "2", None))
        item = self.table_species.horizontalHeaderItem(0)
        item.setText(_translate("QSi_Window", "Label", None))
        item = self.table_species.horizontalHeaderItem(1)
        item.setText(_translate("QSi_Window", "Initial Titre", None))
        item = self.table_species.horizontalHeaderItem(2)
        item.setText(_translate("QSi_Window", "Final Titre", None))
        item = self.table_species.horizontalHeaderItem(3)
        item.setText(_translate("QSi_Window", "pX?", None))
        __sortingEnabled = self.table_species.isSortingEnabled()
        self.table_species.setSortingEnabled(False)
        item = self.table_species.item(0, 0)
        item.setText(_translate("QSi_Window", "L", None))
        item = self.table_species.item(0, 1)
        item.setText(_translate("QSi_Window", "0.1", None))
        item = self.table_species.item(0, 2)
        item.setText(_translate("QSi_Window", "0.1", None))
        item = self.table_species.item(1, 0)
        item.setText(_translate("QSi_Window", "H", None))
        item = self.table_species.item(1, 1)
        item.setText(_translate("QSi_Window", "2", None))
        item = self.table_species.item(1, 2)
        item.setText(_translate("QSi_Window", "12", None))
        self.table_species.setSortingEnabled(__sortingEnabled)
        item = self.table_titration.verticalHeaderItem(0)
        item.setText(_translate("QSi_Window", "1", None))
        item = self.table_titration.verticalHeaderItem(1)
        item.setText(_translate("QSi_Window", "2", None))
        item = self.table_titration.horizontalHeaderItem(0)
        item.setText(_translate("QSi_Window", "Label", None))
        item = self.table_titration.horizontalHeaderItem(1)
        item.setText(_translate("QSi_Window", "Initial", None))
        item = self.table_titration.horizontalHeaderItem(2)
        item.setText(_translate("QSi_Window", "Buret", None))
        __sortingEnabled = self.table_titration.isSortingEnabled()
        self.table_titration.setSortingEnabled(False)
        item = self.table_titration.item(0, 0)
        item.setText(_translate("QSi_Window", "L", None))
        item = self.table_titration.item(0, 1)
        item.setText(_translate("QSi_Window", "10.0", None))
        item = self.table_titration.item(0, 2)
        item.setText(_translate("QSi_Window", "0", None))
        item = self.table_titration.item(1, 0)
        item.setText(_translate("QSi_Window", "H", None))
        item = self.table_titration.item(1, 1)
        item.setText(_translate("QSi_Window", "20.0", None))
        item = self.table_titration.item(1, 2)
        item.setText(_translate("QSi_Window", "-0.1", None))
        self.table_titration.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("QSi_Window", "Initial", None))
        self.label_5.setText(_translate("QSi_Window", "Final", None))
        self.label_3.setText(_translate("QSi_Window", "Volume", None))
        self.table_model.setToolTip(_translate("QSi_Window", "<html><head/><body><p>Constants must be a float number representing the constant in log10 units in the format 12.13(4) where the number in parenthesis is optional and represents the error.</p></body></html>", None))
        item = self.table_model.verticalHeaderItem(0)
        item.setText(_translate("QSi_Window", "1", None))
        item = self.table_model.verticalHeaderItem(1)
        item.setText(_translate("QSi_Window", "2", None))
        item = self.table_model.horizontalHeaderItem(0)
        item.setText(_translate("QSi_Window", "constant", None))
        item = self.table_model.horizontalHeaderItem(1)
        item.setText(_translate("QSi_Window", "L", None))
        item = self.table_model.horizontalHeaderItem(2)
        item.setText(_translate("QSi_Window", "H", None))
        __sortingEnabled = self.table_model.isSortingEnabled()
        self.table_model.setSortingEnabled(False)
        item = self.table_model.item(0, 0)
        item.setText(_translate("QSi_Window", "8.08", None))
        item = self.table_model.item(0, 1)
        item.setText(_translate("QSi_Window", "1", None))
        item = self.table_model.item(0, 2)
        item.setText(_translate("QSi_Window", "1", None))
        item = self.table_model.item(1, 0)
        item.setText(_translate("QSi_Window", "-13.73", None))
        item = self.table_model.item(1, 1)
        item.setText(_translate("QSi_Window", "0", None))
        item = self.table_model.item(1, 2)
        item.setText(_translate("QSi_Window", "-1", None))
        self.table_model.setSortingEnabled(__sortingEnabled)
        self.pb_addbeta.setText(_translate("QSi_Window", "Add ß", None))
        self.pb_removebeta.setText(_translate("QSi_Window", "Remove ß", None))
        self.pb_addreag.setText(_translate("QSi_Window", "Add reagent", None))
        self.pb_removereag.setText(_translate("QSi_Window", "Remove reagent", None))
        self.pb_go.setText(_translate("QSi_Window", "Go!", None))
        self.label_6.setText(_translate("QSi_Window", "Ignore lower than:", None))
        self.label_7.setText(_translate("QSi_Window", "Unlabel lower than:", None))
        self.menuFile.setTitle(_translate("QSi_Window", "File", None))
        self.menuPlot.setTitle(_translate("QSi_Window", "Plot", None))
        self.actionNew.setText(_translate("QSi_Window", "New", None))
        self.actionOpen.setText(_translate("QSi_Window", "Open", None))
        self.actionSave.setText(_translate("QSi_Window", "Save", None))
        self.actionSave_as.setText(_translate("QSi_Window", "Save as", None))
        self.actionExit.setText(_translate("QSi_Window", "Exit", None))
        self.actionPlot_unplot.setText(_translate("QSi_Window", "Plot/unplot", None))
        self.actionAddittional_data.setText(_translate("QSi_Window", "Addittional data", None))
        self.actionExport_Graph.setText(_translate("QSi_Window", "Export Graph", None))
        self.actionExport_Data.setText(_translate("QSi_Window", "Export Data", None))

