# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/calords.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalorDSWidget(object):
    def setupUi(self, CalorDSWidget):
        CalorDSWidget.setObjectName("CalorDSWidget")
        CalorDSWidget.resize(565, 319)
        self.verticalLayout = QtWidgets.QVBoxLayout(CalorDSWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_2 = QtWidgets.QSplitter(CalorDSWidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.vl_1 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.vl_1.setContentsMargins(0, 0, 0, 0)
        self.vl_1.setObjectName("vl_1")
        self.table_titration = QtWidgets.QTableWidget(self.layoutWidget)
        self.table_titration.setObjectName("table_titration")
        self.table_titration.setColumnCount(4)
        self.table_titration.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(1, 2, item)
        self.table_titration.horizontalHeader().setDefaultSectionSize(65)
        self.table_titration.horizontalHeader().setMinimumSectionSize(20)
        self.table_titration.verticalHeader().setVisible(False)
        self.table_titration.verticalHeader().setCascadingSectionResizes(True)
        self.table_titration.verticalHeader().setDefaultSectionSize(30)
        self.table_titration.verticalHeader().setMinimumSectionSize(15)
        self.vl_1.addWidget(self.table_titration)
        self.gl_1 = QtWidgets.QGridLayout()
        self.gl_1.setObjectName("gl_1")
        self.lbl_V0 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_V0.setObjectName("lbl_V0")
        self.gl_1.addWidget(self.lbl_V0, 0, 0, 1, 1)
        self.dsb_errV0 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.dsb_errV0.setDecimals(3)
        self.dsb_errV0.setObjectName("dsb_errV0")
        self.gl_1.addWidget(self.dsb_errV0, 0, 3, 1, 1)
        self.lbl_pm1 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_pm1.sizePolicy().hasHeightForWidth())
        self.lbl_pm1.setSizePolicy(sizePolicy)
        self.lbl_pm1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_pm1.setObjectName("lbl_pm1")
        self.gl_1.addWidget(self.lbl_pm1, 0, 2, 1, 1)
        self.dsb_V0 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.dsb_V0.setDecimals(3)
        self.dsb_V0.setObjectName("dsb_V0")
        self.gl_1.addWidget(self.dsb_V0, 0, 1, 1, 1)
        self.vl_1.addLayout(self.gl_1)
        self.table_data = QtWidgets.QTableWidget(self.splitter_2)
        self.table_data.setEnabled(True)
        self.table_data.setObjectName("table_data")
        self.table_data.setColumnCount(2)
        self.table_data.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.table_data.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_data.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_data.setHorizontalHeaderItem(1, item)
        self.table_data.horizontalHeader().setDefaultSectionSize(65)
        self.verticalLayout.addWidget(self.splitter_2)

        self.retranslateUi(CalorDSWidget)
        QtCore.QMetaObject.connectSlotsByName(CalorDSWidget)

    def retranslateUi(self, CalorDSWidget):
        _translate = QtCore.QCoreApplication.translate
        CalorDSWidget.setWindowTitle(_translate("CalorDSWidget", "Form"))
        item = self.table_titration.verticalHeaderItem(0)
        item.setText(_translate("CalorDSWidget", "1"))
        item = self.table_titration.verticalHeaderItem(1)
        item.setText(_translate("CalorDSWidget", "2"))
        item = self.table_titration.horizontalHeaderItem(0)
        item.setText(_translate("CalorDSWidget", "Label"))
        item = self.table_titration.horizontalHeaderItem(1)
        item.setText(_translate("CalorDSWidget", "Initial"))
        item = self.table_titration.horizontalHeaderItem(2)
        item.setText(_translate("CalorDSWidget", "Buret"))
        item = self.table_titration.horizontalHeaderItem(3)
        item.setText(_translate("CalorDSWidget", "Flag"))
        __sortingEnabled = self.table_titration.isSortingEnabled()
        self.table_titration.setSortingEnabled(False)
        item = self.table_titration.item(0, 0)
        item.setText(_translate("CalorDSWidget", "L"))
        item = self.table_titration.item(0, 1)
        item.setText(_translate("CalorDSWidget", "0.001"))
        item = self.table_titration.item(0, 2)
        item.setText(_translate("CalorDSWidget", "0"))
        item = self.table_titration.item(1, 0)
        item.setText(_translate("CalorDSWidget", "H"))
        item = self.table_titration.item(1, 1)
        item.setText(_translate("CalorDSWidget", "0.005"))
        item = self.table_titration.item(1, 2)
        item.setText(_translate("CalorDSWidget", "-0.1"))
        self.table_titration.setSortingEnabled(__sortingEnabled)
        self.lbl_V0.setText(_translate("CalorDSWidget", "V0"))
        self.lbl_pm1.setText(_translate("CalorDSWidget", "±"))
        item = self.table_data.verticalHeaderItem(0)
        item.setText(_translate("CalorDSWidget", "1"))
        item = self.table_data.horizontalHeaderItem(0)
        item.setText(_translate("CalorDSWidget", "titre"))
        item = self.table_data.horizontalHeaderItem(1)
        item.setText(_translate("CalorDSWidget", "Q"))
