# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/csolver.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CSolverWidget(object):
    def setupUi(self, CSolverWidget):
        CSolverWidget.setObjectName("CSolverWidget")
        CSolverWidget.resize(581, 418)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(CSolverWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(CSolverWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.toolbox = QtWidgets.QToolBox(self.splitter)
        self.toolbox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolbox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolbox.setObjectName("toolbox")
        self.pgStarting = QtWidgets.QWidget()
        self.pgStarting.setGeometry(QtCore.QRect(0, 0, 306, 210))
        self.pgStarting.setObjectName("pgStarting")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.pgStarting)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pbInitialVals = QtWidgets.QPushButton(self.pgStarting)
        self.pbInitialVals.setObjectName("pbInitialVals")
        self.verticalLayout.addWidget(self.pbInitialVals)
        self.pbStartAnalC = QtWidgets.QPushButton(self.pgStarting)
        self.pbStartAnalC.setObjectName("pbStartAnalC")
        self.verticalLayout.addWidget(self.pbStartAnalC)
        self.pbStartFV = QtWidgets.QPushButton(self.pgStarting)
        self.pbStartFV.setObjectName("pbStartFV")
        self.verticalLayout.addWidget(self.pbStartFV)
        self.pbUndo = QtWidgets.QPushButton(self.pgStarting)
        self.pbUndo.setEnabled(False)
        self.pbUndo.setObjectName("pbUndo")
        self.verticalLayout.addWidget(self.pbUndo)
        self.pbInitialGuess = QtWidgets.QPushButton(self.pgStarting)
        self.pbInitialGuess.setObjectName("pbInitialGuess")
        self.verticalLayout.addWidget(self.pbInitialGuess)
        self.toolbox.addItem(self.pgStarting, "")
        self.pgDamping = QtWidgets.QWidget()
        self.pgDamping.setGeometry(QtCore.QRect(0, 0, 306, 210))
        self.pgDamping.setObjectName("pgDamping")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pgDamping)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_pcf = QtWidgets.QPushButton(self.pgDamping)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_pcf.sizePolicy().hasHeightForWidth())
        self.pb_pcf.setSizePolicy(sizePolicy)
        self.pb_pcf.setObjectName("pb_pcf")
        self.horizontalLayout.addWidget(self.pb_pcf)
        self.label = QtWidgets.QLabel(self.pgDamping)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.le_pcf_tol = QtWidgets.QLineEdit(self.pgDamping)
        self.le_pcf_tol.setObjectName("le_pcf_tol")
        self.horizontalLayout.addWidget(self.le_pcf_tol)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.pgDamping)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.dsb_dampfactor = QtWidgets.QDoubleSpinBox(self.pgDamping)
        self.dsb_dampfactor.setDecimals(1)
        self.dsb_dampfactor.setMaximum(20.0)
        self.dsb_dampfactor.setProperty("value", 10.0)
        self.dsb_dampfactor.setObjectName("dsb_dampfactor")
        self.horizontalLayout_4.addWidget(self.dsb_dampfactor)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.pbDamping = QtWidgets.QPushButton(self.pgDamping)
        self.pbDamping.setObjectName("pbDamping")
        self.verticalLayout_3.addWidget(self.pbDamping)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pbDamp1 = QtWidgets.QPushButton(self.pgDamping)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbDamp1.sizePolicy().hasHeightForWidth())
        self.pbDamp1.setSizePolicy(sizePolicy)
        self.pbDamp1.setObjectName("pbDamp1")
        self.horizontalLayout_3.addWidget(self.pbDamp1)
        self.sb_dampspecies = QtWidgets.QSpinBox(self.pgDamping)
        self.sb_dampspecies.setObjectName("sb_dampspecies")
        self.horizontalLayout_3.addWidget(self.sb_dampspecies)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.pbFixOL = QtWidgets.QPushButton(self.pgDamping)
        self.pbFixOL.setObjectName("pbFixOL")
        self.verticalLayout_3.addWidget(self.pbFixOL)
        self.toolbox.addItem(self.pgDamping, "")
        self.pgFitting = QtWidgets.QWidget()
        self.pgFitting.setGeometry(QtCore.QRect(0, 0, 293, 503))
        self.pgFitting.setObjectName("pgFitting")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pgFitting)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cbScaling = QtWidgets.QCheckBox(self.pgFitting)
        self.cbScaling.setChecked(False)
        self.cbScaling.setObjectName("cbScaling")
        self.verticalLayout_5.addWidget(self.cbScaling)
        self.cbDamping = QtWidgets.QCheckBox(self.pgFitting)
        self.cbDamping.setObjectName("cbDamping")
        self.verticalLayout_5.addWidget(self.cbDamping)
        self.cb0OffD = QtWidgets.QCheckBox(self.pgFitting)
        self.cb0OffD.setObjectName("cb0OffD")
        self.verticalLayout_5.addWidget(self.cb0OffD)
        self.cbMask = QtWidgets.QCheckBox(self.pgFitting)
        self.cbMask.setObjectName("cbMask")
        self.verticalLayout_5.addWidget(self.cbMask)
        self.cbStepLimiter = QtWidgets.QCheckBox(self.pgFitting)
        self.cbStepLimiter.setChecked(False)
        self.cbStepLimiter.setObjectName("cbStepLimiter")
        self.verticalLayout_5.addWidget(self.cbStepLimiter)
        self.cbForcer = QtWidgets.QCheckBox(self.pgFitting)
        self.cbForcer.setObjectName("cbForcer")
        self.verticalLayout_5.addWidget(self.cbForcer)
        self.cbStepwise = QtWidgets.QCheckBox(self.pgFitting)
        self.cbStepwise.setObjectName("cbStepwise")
        self.verticalLayout_5.addWidget(self.cbStepwise)
        self.cbLogFit = QtWidgets.QCheckBox(self.pgFitting)
        self.cbLogFit.setObjectName("cbLogFit")
        self.verticalLayout_5.addWidget(self.cbLogFit)
        self.groupBox = QtWidgets.QGroupBox(self.pgFitting)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.rb_RefAll = QtWidgets.QRadioButton(self.groupBox)
        self.rb_RefAll.setChecked(True)
        self.rb_RefAll.setObjectName("rb_RefAll")
        self.verticalLayout_4.addWidget(self.rb_RefAll)
        self.rbRefInter = QtWidgets.QRadioButton(self.groupBox)
        self.rbRefInter.setObjectName("rbRefInter")
        self.verticalLayout_4.addWidget(self.rbRefInter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.sbRefFrom = QtWidgets.QSpinBox(self.groupBox)
        self.sbRefFrom.setMinimum(1)
        self.sbRefFrom.setObjectName("sbRefFrom")
        self.horizontalLayout_2.addWidget(self.sbRefFrom)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.sbRefTo = QtWidgets.QSpinBox(self.groupBox)
        self.sbRefTo.setMinimum(1)
        self.sbRefTo.setProperty("value", 1)
        self.sbRefTo.setObjectName("sbRefTo")
        self.horizontalLayout_2.addWidget(self.sbRefTo)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.pbIter1 = QtWidgets.QPushButton(self.pgFitting)
        self.pbIter1.setObjectName("pbIter1")
        self.verticalLayout_5.addWidget(self.pbIter1)
        self.pbIter10 = QtWidgets.QPushButton(self.pgFitting)
        self.pbIter10.setObjectName("pbIter10")
        self.verticalLayout_5.addWidget(self.pbIter10)
        self.pbIter100 = QtWidgets.QPushButton(self.pgFitting)
        self.pbIter100.setObjectName("pbIter100")
        self.verticalLayout_5.addWidget(self.pbIter100)
        self.pbIter1000 = QtWidgets.QPushButton(self.pgFitting)
        self.pbIter1000.setObjectName("pbIter1000")
        self.verticalLayout_5.addWidget(self.pbIter1000)
        self.toolbox.addItem(self.pgFitting, "")
        self.pgPlot = QtWidgets.QWidget()
        self.pgPlot.setGeometry(QtCore.QRect(0, 0, 306, 210))
        self.pgPlot.setObjectName("pgPlot")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.pgPlot)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.pgPlot)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.rb_plotall = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_plotall.setChecked(True)
        self.rb_plotall.setObjectName("rb_plotall")
        self.verticalLayout_7.addWidget(self.rb_plotall)
        self.rb_plotindependent = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_plotindependent.setObjectName("rb_plotindependent")
        self.verticalLayout_7.addWidget(self.rb_plotindependent)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.toolbox.addItem(self.pgPlot, "")
        self.pgTools = QtWidgets.QWidget()
        self.pgTools.setGeometry(QtCore.QRect(0, 0, 306, 210))
        self.pgTools.setObjectName("pgTools")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.pgTools)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pbSmooth = QtWidgets.QPushButton(self.pgTools)
        self.pbSmooth.setObjectName("pbSmooth")
        self.verticalLayout_8.addWidget(self.pbSmooth)
        self.pbInterpolate = QtWidgets.QPushButton(self.pgTools)
        self.pbInterpolate.setObjectName("pbInterpolate")
        self.verticalLayout_8.addWidget(self.pbInterpolate)
        self.pb_zeronans = QtWidgets.QPushButton(self.pgTools)
        self.pb_zeronans.setObjectName("pb_zeronans")
        self.verticalLayout_8.addWidget(self.pb_zeronans)
        self.pbSave = QtWidgets.QPushButton(self.pgTools)
        self.pbSave.setObjectName("pbSave")
        self.verticalLayout_8.addWidget(self.pbSave)
        self.pbFortran = QtWidgets.QPushButton(self.pgTools)
        self.pbFortran.setObjectName("pbFortran")
        self.verticalLayout_8.addWidget(self.pbFortran)
        self.toolbox.addItem(self.pgTools, "")
        self.canvas = QtWidgets.QWidget(self.splitter)
        self.canvas.setObjectName("canvas")
        self.verticalLayout_2.addWidget(self.splitter)
        self.buttonBox = QtWidgets.QDialogButtonBox(CSolverWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(CSolverWidget)
        self.toolbox.setCurrentIndex(1)
        self.buttonBox.accepted.connect(CSolverWidget.accept)
        self.buttonBox.rejected.connect(CSolverWidget.reject)
        QtCore.QMetaObject.connectSlotsByName(CSolverWidget)

    def retranslateUi(self, CSolverWidget):
        _translate = QtCore.QCoreApplication.translate
        CSolverWidget.setWindowTitle(_translate("CSolverWidget", "Dialog"))
        self.pbInitialVals.setText(_translate("CSolverWidget", "Initial values"))
        self.pbStartAnalC.setText(_translate("CSolverWidget", "Anal. concs."))
        self.pbStartFV.setText(_translate("CSolverWidget", "Fixed value"))
        self.pbUndo.setText(_translate("CSolverWidget", "Undo"))
        self.pbInitialGuess.setText(_translate("CSolverWidget", "Initial Guess"))
        self.toolbox.setItemText(self.toolbox.indexOf(self.pgStarting), _translate("CSolverWidget", "Starting values"))
        self.pb_pcf.setText(_translate("CSolverWidget", "PCF"))
        self.label.setText(_translate("CSolverWidget", "tolerance"))
        self.le_pcf_tol.setText(_translate("CSolverWidget", "1e-6"))
        self.label_4.setText(_translate("CSolverWidget", "Damping factor:"))
        self.pbDamping.setText(_translate("CSolverWidget", "Damping"))
        self.pbDamp1.setText(_translate("CSolverWidget", "Damp once"))
        self.pbFixOL.setText(_translate("CSolverWidget", "Fix outliers"))
        self.toolbox.setItemText(self.toolbox.indexOf(self.pgDamping), _translate("CSolverWidget", "Damping"))
        self.cbScaling.setText(_translate("CSolverWidget", "Scaling"))
        self.cbDamping.setText(_translate("CSolverWidget", "Damping"))
        self.cb0OffD.setText(_translate("CSolverWidget", "Zero off-diagonal"))
        self.cbMask.setText(_translate("CSolverWidget", "Mask"))
        self.cbStepLimiter.setText(_translate("CSolverWidget", "Step limiter"))
        self.cbForcer.setText(_translate("CSolverWidget", "Forcer"))
        self.cbStepwise.setText(_translate("CSolverWidget", "Stepwise"))
        self.cbLogFit.setText(_translate("CSolverWidget", "Log fitting"))
        self.groupBox.setTitle(_translate("CSolverWidget", "Refine"))
        self.rb_RefAll.setText(_translate("CSolverWidget", "All"))
        self.rbRefInter.setText(_translate("CSolverWidget", "Interval"))
        self.label_2.setText(_translate("CSolverWidget", "From"))
        self.label_3.setText(_translate("CSolverWidget", "To"))
        self.pbIter1.setText(_translate("CSolverWidget", "iter 1"))
        self.pbIter10.setText(_translate("CSolverWidget", "iter 10"))
        self.pbIter100.setText(_translate("CSolverWidget", "iter 100"))
        self.pbIter1000.setText(_translate("CSolverWidget", "iter 1000"))
        self.toolbox.setItemText(self.toolbox.indexOf(self.pgFitting), _translate("CSolverWidget", "Fitting"))
        self.groupBox_2.setTitle(_translate("CSolverWidget", "Components"))
        self.rb_plotall.setText(_translate("CSolverWidget", "All"))
        self.rb_plotindependent.setText(_translate("CSolverWidget", "Independent components"))
        self.toolbox.setItemText(self.toolbox.indexOf(self.pgPlot), _translate("CSolverWidget", "Plot"))
        self.pbSmooth.setText(_translate("CSolverWidget", "Smooth"))
        self.pbInterpolate.setText(_translate("CSolverWidget", "Interpolate"))
        self.pb_zeronans.setText(_translate("CSolverWidget", "Zero NaNs"))
        self.pbSave.setText(_translate("CSolverWidget", "Save Results"))
        self.pbFortran.setText(_translate("CSolverWidget", "Fortran engine"))
        self.toolbox.setItemText(self.toolbox.indexOf(self.pgTools), _translate("CSolverWidget", "Tools"))
