# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/constants.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Constants(object):
    def setupUi(self, Constants):
        Constants.setObjectName("Constants")
        Constants.resize(261, 147)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Constants)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cb_reagent1 = QtWidgets.QComboBox(Constants)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_reagent1.sizePolicy().hasHeightForWidth())
        self.cb_reagent1.setSizePolicy(sizePolicy)
        self.cb_reagent1.setObjectName("cb_reagent1")
        self.horizontalLayout_2.addWidget(self.cb_reagent1)
        self.label = QtWidgets.QLabel(Constants)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.cb_reagent2 = QtWidgets.QComboBox(Constants)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_reagent2.sizePolicy().hasHeightForWidth())
        self.cb_reagent2.setSizePolicy(sizePolicy)
        self.cb_reagent2.setObjectName("cb_reagent2")
        self.horizontalLayout_2.addWidget(self.cb_reagent2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(Constants)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cb_reagent3 = QtWidgets.QComboBox(Constants)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_reagent3.sizePolicy().hasHeightForWidth())
        self.cb_reagent3.setSizePolicy(sizePolicy)
        self.cb_reagent3.setObjectName("cb_reagent3")
        self.horizontalLayout.addWidget(self.cb_reagent3)
        self.label_2 = QtWidgets.QLabel(Constants)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.cb_reagent4 = QtWidgets.QComboBox(Constants)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_reagent4.sizePolicy().hasHeightForWidth())
        self.cb_reagent4.setSizePolicy(sizePolicy)
        self.cb_reagent4.setObjectName("cb_reagent4")
        self.horizontalLayout.addWidget(self.cb_reagent4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.lbl_result = QtWidgets.QLabel(Constants)
        self.lbl_result.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_result.setObjectName("lbl_result")
        self.verticalLayout_2.addWidget(self.lbl_result)
        self.buttonBox = QtWidgets.QDialogButtonBox(Constants)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Constants)
        self.buttonBox.accepted.connect(Constants.accept)
        self.buttonBox.rejected.connect(Constants.reject)
        QtCore.QMetaObject.connectSlotsByName(Constants)

    def retranslateUi(self, Constants):
        _translate = QtCore.QCoreApplication.translate
        Constants.setWindowTitle(_translate("Constants", "Stepwise Constants"))
        self.label.setText(_translate("Constants", "x"))
        self.label_2.setText(_translate("Constants", "x"))
        self.lbl_result.setText(_translate("Constants", "logK = "))

