# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/calords.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalorWidget(object):
    def setupUi(self, CalorWidget):
        CalorWidget.setObjectName("CalorWidget")
        CalorWidget.resize(576, 321)
        self.verticalLayout = QtWidgets.QVBoxLayout(CalorWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(CalorWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cb_titration = QtWidgets.QComboBox(CalorWidget)
        self.cb_titration.setObjectName("cb_titration")
        self.horizontalLayout.addWidget(self.cb_titration)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.table_data = QtWidgets.QTableWidget(CalorWidget)
        self.table_data.setEnabled(True)
        self.table_data.setObjectName("table_data")
        self.table_data.setColumnCount(2)
        self.table_data.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.table_data.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_data.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_data.setHorizontalHeaderItem(1, item)
        self.table_data.horizontalHeader().setDefaultSectionSize(65)
        self.verticalLayout.addWidget(self.table_data)

        self.retranslateUi(CalorWidget)
        QtCore.QMetaObject.connectSlotsByName(CalorWidget)

    def retranslateUi(self, CalorWidget):
        _translate = QtCore.QCoreApplication.translate
        CalorWidget.setWindowTitle(_translate("CalorWidget", "Form"))
        self.label.setText(_translate("CalorWidget", "Titration"))
        item = self.table_data.verticalHeaderItem(0)
        item.setText(_translate("CalorWidget", "1"))
        item = self.table_data.horizontalHeaderItem(0)
        item.setText(_translate("CalorWidget", "titre"))
        item = self.table_data.horizontalHeaderItem(1)
        item.setText(_translate("CalorWidget", "Q"))
