# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/emfds.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EmfDSWidget(object):
    def setupUi(self, EmfDSWidget):
        EmfDSWidget.setObjectName("EmfDSWidget")
        EmfDSWidget.resize(556, 331)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(EmfDSWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hsplitter = QtWidgets.QSplitter(EmfDSWidget)
        self.hsplitter.setOrientation(QtCore.Qt.Horizontal)
        self.hsplitter.setObjectName("hsplitter")
        self.vsplitter = QtWidgets.QSplitter(self.hsplitter)
        self.vsplitter.setOrientation(QtCore.Qt.Vertical)
        self.vsplitter.setObjectName("vsplitter")
        self.layoutWidget = QtWidgets.QWidget(self.vsplitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.le_title = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_title.setObjectName("le_title")
        self.horizontalLayout_2.addWidget(self.le_title)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_V0 = QtWidgets.QLabel(self.layoutWidget)
        self.label_V0.setObjectName("label_V0")
        self.horizontalLayout.addWidget(self.label_V0)
        self.dsb_V0 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.dsb_V0.setDecimals(3)
        self.dsb_V0.setMaximum(999.99)
        self.dsb_V0.setObjectName("dsb_V0")
        self.horizontalLayout.addWidget(self.dsb_V0)
        self.label_errV = QtWidgets.QLabel(self.layoutWidget)
        self.label_errV.setObjectName("label_errV")
        self.horizontalLayout.addWidget(self.label_errV)
        self.dsb_errV = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.dsb_errV.setDecimals(3)
        self.dsb_errV.setMaximum(9.99)
        self.dsb_errV.setSingleStep(0.1)
        self.dsb_errV.setProperty("value", 0.03)
        self.dsb_errV.setObjectName("dsb_errV")
        self.horizontalLayout.addWidget(self.dsb_errV)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.table_titration = QtWidgets.QTableWidget(self.layoutWidget)
        self.table_titration.setObjectName("table_titration")
        self.table_titration.setColumnCount(4)
        self.table_titration.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(1, 2, item)
        self.table_titration.horizontalHeader().setDefaultSectionSize(65)
        self.table_titration.horizontalHeader().setMinimumSectionSize(20)
        self.table_titration.verticalHeader().setVisible(False)
        self.table_titration.verticalHeader().setCascadingSectionResizes(True)
        self.table_titration.verticalHeader().setDefaultSectionSize(30)
        self.table_titration.verticalHeader().setMinimumSectionSize(15)
        self.verticalLayout.addWidget(self.table_titration)
        self.table_params = QtWidgets.QTableWidget(self.vsplitter)
        self.table_params.setObjectName("table_params")
        self.table_params.setColumnCount(1)
        self.table_params.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.table_params.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_params.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_params.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_params.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_params.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_params.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_params.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_params.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_params.setItem(3, 0, item)
        self.table_params.horizontalHeader().setDefaultSectionSize(80)
        self.table_data = QtWidgets.QTableWidget(self.hsplitter)
        self.table_data.setEnabled(True)
        self.table_data.setObjectName("table_data")
        self.table_data.setColumnCount(2)
        self.table_data.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.table_data.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_data.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_data.setHorizontalHeaderItem(1, item)
        self.table_data.horizontalHeader().setDefaultSectionSize(65)
        self.verticalLayout_2.addWidget(self.hsplitter)

        self.retranslateUi(EmfDSWidget)
        QtCore.QMetaObject.connectSlotsByName(EmfDSWidget)

    def retranslateUi(self, EmfDSWidget):
        _translate = QtCore.QCoreApplication.translate
        EmfDSWidget.setWindowTitle(_translate("EmfDSWidget", "Form"))
        self.label_V0.setText(_translate("EmfDSWidget", "V0"))
        self.label_errV.setText(_translate("EmfDSWidget", "error V"))
        item = self.table_titration.verticalHeaderItem(0)
        item.setText(_translate("EmfDSWidget", "1"))
        item = self.table_titration.verticalHeaderItem(1)
        item.setText(_translate("EmfDSWidget", "2"))
        item = self.table_titration.horizontalHeaderItem(0)
        item.setText(_translate("EmfDSWidget", "Label"))
        item = self.table_titration.horizontalHeaderItem(1)
        item.setText(_translate("EmfDSWidget", "Initial"))
        item = self.table_titration.horizontalHeaderItem(2)
        item.setText(_translate("EmfDSWidget", "Buret"))
        item = self.table_titration.horizontalHeaderItem(3)
        item.setText(_translate("EmfDSWidget", "Flag"))
        __sortingEnabled = self.table_titration.isSortingEnabled()
        self.table_titration.setSortingEnabled(False)
        item = self.table_titration.item(0, 0)
        item.setText(_translate("EmfDSWidget", "L"))
        item = self.table_titration.item(0, 1)
        item.setText(_translate("EmfDSWidget", "0.001"))
        item = self.table_titration.item(0, 2)
        item.setText(_translate("EmfDSWidget", "0"))
        item = self.table_titration.item(1, 0)
        item.setText(_translate("EmfDSWidget", "H"))
        item = self.table_titration.item(1, 1)
        item.setText(_translate("EmfDSWidget", "0.005"))
        item = self.table_titration.item(1, 2)
        item.setText(_translate("EmfDSWidget", "-0.1"))
        self.table_titration.setSortingEnabled(__sortingEnabled)
        item = self.table_params.verticalHeaderItem(0)
        item.setText(_translate("EmfDSWidget", "emf0"))
        item = self.table_params.verticalHeaderItem(1)
        item.setText(_translate("EmfDSWidget", "error"))
        item = self.table_params.verticalHeaderItem(2)
        item.setText(_translate("EmfDSWidget", "flag"))
        item = self.table_params.verticalHeaderItem(3)
        item.setText(_translate("EmfDSWidget", "n"))
        item = self.table_params.verticalHeaderItem(4)
        item.setText(_translate("EmfDSWidget", "active"))
        item = self.table_params.horizontalHeaderItem(0)
        item.setText(_translate("EmfDSWidget", "electrode0"))
        __sortingEnabled = self.table_params.isSortingEnabled()
        self.table_params.setSortingEnabled(False)
        item = self.table_params.item(0, 0)
        item.setText(_translate("EmfDSWidget", "380.0"))
        item = self.table_params.item(1, 0)
        item.setText(_translate("EmfDSWidget", "0.02"))
        item = self.table_params.item(3, 0)
        item.setText(_translate("EmfDSWidget", "1"))
        self.table_params.setSortingEnabled(__sortingEnabled)
        item = self.table_data.verticalHeaderItem(0)
        item.setText(_translate("EmfDSWidget", "1"))
        item = self.table_data.horizontalHeaderItem(0)
        item.setText(_translate("EmfDSWidget", "V"))
        item = self.table_data.horizontalHeaderItem(1)
        item.setText(_translate("EmfDSWidget", "emf"))
