# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/ionicst.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IonicWidget(object):
    def setupUi(self, IonicWidget):
        IonicWidget.setObjectName("IonicWidget")
        IonicWidget.resize(459, 294)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(IonicWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.table_titration = QtWidgets.QTableWidget(IonicWidget)
        self.table_titration.setObjectName("table_titration")
        self.table_titration.setColumnCount(4)
        self.table_titration.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(2, 3, item)
        self.table_titration.verticalHeader().setVisible(False)
        self.table_titration.verticalHeader().setCascadingSectionResizes(True)
        self.verticalLayout_2.addWidget(self.table_titration)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gl_volume = QtWidgets.QGridLayout()
        self.gl_volume.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gl_volume.setObjectName("gl_volume")
        self.lbl_Vi = QtWidgets.QLabel(IonicWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_Vi.sizePolicy().hasHeightForWidth())
        self.lbl_Vi.setSizePolicy(sizePolicy)
        self.lbl_Vi.setObjectName("lbl_Vi")
        self.gl_volume.addWidget(self.lbl_Vi, 0, 1, 1, 1)
        self.lbl_Vf = QtWidgets.QLabel(IonicWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_Vf.sizePolicy().hasHeightForWidth())
        self.lbl_Vf.setSizePolicy(sizePolicy)
        self.lbl_Vf.setObjectName("lbl_Vf")
        self.gl_volume.addWidget(self.lbl_Vf, 0, 2, 1, 1)
        self.lbl_V = QtWidgets.QLabel(IonicWidget)
        self.lbl_V.setObjectName("lbl_V")
        self.gl_volume.addWidget(self.lbl_V, 1, 0, 1, 1)
        self.dsb_V0 = QtWidgets.QDoubleSpinBox(IonicWidget)
        self.dsb_V0.setMaximum(1000.0)
        self.dsb_V0.setProperty("value", 10.0)
        self.dsb_V0.setObjectName("dsb_V0")
        self.gl_volume.addWidget(self.dsb_V0, 1, 1, 1, 1)
        self.dsb_Vf = QtWidgets.QDoubleSpinBox(IonicWidget)
        self.dsb_Vf.setMaximum(1000.0)
        self.dsb_Vf.setProperty("value", 11.0)
        self.dsb_Vf.setObjectName("dsb_Vf")
        self.gl_volume.addWidget(self.dsb_Vf, 1, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gl_volume)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pb_plus = QtWidgets.QPushButton(IonicWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_plus.sizePolicy().hasHeightForWidth())
        self.pb_plus.setSizePolicy(sizePolicy)
        self.pb_plus.setMinimumSize(QtCore.QSize(10, 0))
        self.pb_plus.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pb_plus.setObjectName("pb_plus")
        self.verticalLayout.addWidget(self.pb_plus)
        self.pb_minus = QtWidgets.QPushButton(IonicWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_minus.sizePolicy().hasHeightForWidth())
        self.pb_minus.setSizePolicy(sizePolicy)
        self.pb_minus.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pb_minus.setObjectName("pb_minus")
        self.verticalLayout.addWidget(self.pb_minus)
        self.verticalLayout.setStretch(1, 10)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(IonicWidget)
        QtCore.QMetaObject.connectSlotsByName(IonicWidget)

    def retranslateUi(self, IonicWidget):
        _translate = QtCore.QCoreApplication.translate
        IonicWidget.setWindowTitle(_translate("IonicWidget", "Form"))
        item = self.table_titration.verticalHeaderItem(0)
        item.setText(_translate("IonicWidget", "1"))
        item = self.table_titration.verticalHeaderItem(1)
        item.setText(_translate("IonicWidget", "2"))
        item = self.table_titration.verticalHeaderItem(2)
        item.setText(_translate("IonicWidget", "3"))
        item = self.table_titration.horizontalHeaderItem(0)
        item.setText(_translate("IonicWidget", "Species"))
        item = self.table_titration.horizontalHeaderItem(1)
        item.setText(_translate("IonicWidget", "Charge"))
        item = self.table_titration.horizontalHeaderItem(2)
        item.setText(_translate("IonicWidget", "Initial"))
        item = self.table_titration.horizontalHeaderItem(3)
        item.setText(_translate("IonicWidget", "Buret"))
        __sortingEnabled = self.table_titration.isSortingEnabled()
        self.table_titration.setSortingEnabled(False)
        item = self.table_titration.item(0, 0)
        item.setText(_translate("IonicWidget", "Na"))
        item = self.table_titration.item(0, 1)
        item.setText(_translate("IonicWidget", "+1"))
        item = self.table_titration.item(0, 2)
        item.setText(_translate("IonicWidget", "0.15"))
        item = self.table_titration.item(0, 3)
        item.setText(_translate("IonicWidget", "0.1"))
        item = self.table_titration.item(1, 0)
        item.setText(_translate("IonicWidget", "Cl"))
        item = self.table_titration.item(1, 1)
        item.setText(_translate("IonicWidget", "-1"))
        item = self.table_titration.item(1, 2)
        item.setText(_translate("IonicWidget", "0.15"))
        item = self.table_titration.item(1, 3)
        item.setText(_translate("IonicWidget", "0"))
        item = self.table_titration.item(2, 0)
        item.setText(_translate("IonicWidget", "OH"))
        item = self.table_titration.item(2, 1)
        item.setText(_translate("IonicWidget", "-1"))
        item = self.table_titration.item(2, 2)
        item.setText(_translate("IonicWidget", "0"))
        item = self.table_titration.item(2, 3)
        item.setText(_translate("IonicWidget", "0.1"))
        self.table_titration.setSortingEnabled(__sortingEnabled)
        self.lbl_Vi.setText(_translate("IonicWidget", "Initial"))
        self.lbl_Vf.setText(_translate("IonicWidget", "Final"))
        self.lbl_V.setText(_translate("IonicWidget", "Volume"))
        self.pb_plus.setText(_translate("IonicWidget", "+"))
        self.pb_minus.setText(_translate("IonicWidget", "-"))
