# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/linepropertiesdialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LinePropertiesDialog(object):
    def setupUi(self, LinePropertiesDialog):
        LinePropertiesDialog.setObjectName("LinePropertiesDialog")
        LinePropertiesDialog.resize(210, 336)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LinePropertiesDialog.sizePolicy().hasHeightForWidth())
        LinePropertiesDialog.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(LinePropertiesDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(LinePropertiesDialog)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.cb_linetype = QtWidgets.QComboBox(LinePropertiesDialog)
        self.cb_linetype.setObjectName("cb_linetype")
        self.horizontalLayout_3.addWidget(self.cb_linetype)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(LinePropertiesDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.sb_thickness = QtWidgets.QDoubleSpinBox(LinePropertiesDialog)
        self.sb_thickness.setDecimals(1)
        self.sb_thickness.setObjectName("sb_thickness")
        self.horizontalLayout_4.addWidget(self.sb_thickness)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(LinePropertiesDialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.cb_color = QtWidgets.QComboBox(LinePropertiesDialog)
        self.cb_color.setObjectName("cb_color")
        self.horizontalLayout_5.addWidget(self.cb_color)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.groupBox = QtWidgets.QGroupBox(LinePropertiesDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(LinePropertiesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(LinePropertiesDialog)
        self.buttonBox.accepted.connect(LinePropertiesDialog.accept)
        self.buttonBox.rejected.connect(LinePropertiesDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(LinePropertiesDialog)

    def retranslateUi(self, LinePropertiesDialog):
        _translate = QtCore.QCoreApplication.translate
        LinePropertiesDialog.setWindowTitle(_translate("LinePropertiesDialog", "Dialog"))
        self.label.setText(_translate("LinePropertiesDialog", "Linetype"))
        self.label_2.setText(_translate("LinePropertiesDialog", "Thickness"))
        self.label_3.setText(_translate("LinePropertiesDialog", "Color"))
        self.groupBox.setTitle(_translate("LinePropertiesDialog", "Error"))
        self.checkBox.setText(_translate("LinePropertiesDialog", "Show"))
        self.label_4.setText(_translate("LinePropertiesDialog", "Color"))
        self.label_5.setText(_translate("LinePropertiesDialog", "Linetype"))
        self.checkBox_2.setText(_translate("LinePropertiesDialog", "Shadow"))

