# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/manualfit.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManualFitWidget(object):
    def setupUi(self, ManualFitWidget):
        ManualFitWidget.setObjectName("ManualFitWidget")
        ManualFitWidget.resize(398, 342)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ManualFitWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabdata = QtWidgets.QTableWidget(ManualFitWidget)
        self.tabdata.setEnabled(True)
        self.tabdata.setObjectName("tabdata")
        self.tabdata.setColumnCount(4)
        self.tabdata.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tabdata.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabdata.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabdata.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabdata.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabdata.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabdata.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabdata.setHorizontalHeaderItem(3, item)
        self.verticalLayout_3.addWidget(self.tabdata)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cb_selectconst = QtWidgets.QComboBox(ManualFitWidget)
        self.cb_selectconst.setObjectName("cb_selectconst")
        self.horizontalLayout_5.addWidget(self.cb_selectconst)
        self.pb_update = QtWidgets.QPushButton(ManualFitWidget)
        self.pb_update.setObjectName("pb_update")
        self.horizontalLayout_5.addWidget(self.pb_update)
        self.pb_close = QtWidgets.QPushButton(ManualFitWidget)
        self.pb_close.setObjectName("pb_close")
        self.horizontalLayout_5.addWidget(self.pb_close)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.slider_constant = QtWidgets.QSlider(ManualFitWidget)
        self.slider_constant.setOrientation(QtCore.Qt.Horizontal)
        self.slider_constant.setObjectName("slider_constant")
        self.verticalLayout.addWidget(self.slider_constant)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_minconst = QtWidgets.QLabel(ManualFitWidget)
        self.lbl_minconst.setObjectName("lbl_minconst")
        self.horizontalLayout.addWidget(self.lbl_minconst)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lbl_current_value = QtWidgets.QLabel(ManualFitWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_current_value.setFont(font)
        self.lbl_current_value.setObjectName("lbl_current_value")
        self.horizontalLayout.addWidget(self.lbl_current_value)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lbl_maxconst = QtWidgets.QLabel(ManualFitWidget)
        self.lbl_maxconst.setObjectName("lbl_maxconst")
        self.horizontalLayout.addWidget(self.lbl_maxconst)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(ManualFitWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.lbl_chisq = QtWidgets.QLabel(ManualFitWidget)
        self.lbl_chisq.setObjectName("lbl_chisq")
        self.horizontalLayout_3.addWidget(self.lbl_chisq)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_negative = QtWidgets.QProgressBar(ManualFitWidget)
        self.pb_negative.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pb_negative.setProperty("value", 24)
        self.pb_negative.setFormat("")
        self.pb_negative.setObjectName("pb_negative")
        self.horizontalLayout_2.addWidget(self.pb_negative)
        self.line = QtWidgets.QFrame(ManualFitWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.pb_positive = QtWidgets.QProgressBar(ManualFitWidget)
        self.pb_positive.setProperty("value", 24)
        self.pb_positive.setTextVisible(False)
        self.pb_positive.setFormat("")
        self.pb_positive.setObjectName("pb_positive")
        self.horizontalLayout_2.addWidget(self.pb_positive)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)

        self.retranslateUi(ManualFitWidget)
        QtCore.QMetaObject.connectSlotsByName(ManualFitWidget)

    def retranslateUi(self, ManualFitWidget):
        _translate = QtCore.QCoreApplication.translate
        ManualFitWidget.setWindowTitle(_translate("ManualFitWidget", "Form"))
        item = self.tabdata.verticalHeaderItem(0)
        item.setText(_translate("ManualFitWidget", "1"))
        item = self.tabdata.verticalHeaderItem(1)
        item.setText(_translate("ManualFitWidget", "2"))
        item = self.tabdata.verticalHeaderItem(2)
        item.setText(_translate("ManualFitWidget", "3"))
        item = self.tabdata.horizontalHeaderItem(0)
        item.setText(_translate("ManualFitWidget", "L"))
        item = self.tabdata.horizontalHeaderItem(1)
        item.setText(_translate("ManualFitWidget", "H"))
        item = self.tabdata.horizontalHeaderItem(2)
        item.setText(_translate("ManualFitWidget", "Value"))
        item = self.tabdata.horizontalHeaderItem(3)
        item.setText(_translate("ManualFitWidget", "Gradient"))
        self.pb_update.setText(_translate("ManualFitWidget", "Accept Values"))
        self.pb_close.setText(_translate("ManualFitWidget", "Close"))
        self.lbl_minconst.setText(_translate("ManualFitWidget", "10.0"))
        self.lbl_current_value.setText(_translate("ManualFitWidget", "10.45"))
        self.lbl_maxconst.setText(_translate("ManualFitWidget", "11.0"))
        self.label_6.setText(_translate("ManualFitWidget", "Chi squared:"))
        self.lbl_chisq.setText(_translate("ManualFitWidget", "-13.71"))
