# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/optionsdialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ApesOptions(object):
    def setupUi(self, ApesOptions):
        ApesOptions.setObjectName("ApesOptions")
        ApesOptions.resize(442, 425)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(ApesOptions)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(ApesOptions)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_general)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.hl_3 = QtWidgets.QHBoxLayout()
        self.hl_3.setObjectName("hl_3")
        self.lbl_verbosity = QtWidgets.QLabel(self.tab_general)
        self.lbl_verbosity.setObjectName("lbl_verbosity")
        self.hl_3.addWidget(self.lbl_verbosity)
        self.cb_verbosity = QtWidgets.QComboBox(self.tab_general)
        self.cb_verbosity.setObjectName("cb_verbosity")
        self.cb_verbosity.addItem("")
        self.cb_verbosity.addItem("")
        self.cb_verbosity.addItem("")
        self.hl_3.addWidget(self.cb_verbosity)
        self.verticalLayout_6.addLayout(self.hl_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_general, "")
        self.tab_plots = QtWidgets.QWidget()
        self.tab_plots.setEnabled(True)
        self.tab_plots.setObjectName("tab_plots")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_plots)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.tab_plots)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.dsb_ignorelwr = QtWidgets.QDoubleSpinBox(self.tab_plots)
        self.dsb_ignorelwr.setSingleStep(0.1)
        self.dsb_ignorelwr.setProperty("value", 0.2)
        self.dsb_ignorelwr.setObjectName("dsb_ignorelwr")
        self.horizontalLayout_5.addWidget(self.dsb_ignorelwr)
        self.label_2 = QtWidgets.QLabel(self.tab_plots)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.dsb_unlabellwr = QtWidgets.QDoubleSpinBox(self.tab_plots)
        self.dsb_unlabellwr.setSingleStep(0.1)
        self.dsb_unlabellwr.setProperty("value", 5.0)
        self.dsb_unlabellwr.setObjectName("dsb_unlabellwr")
        self.horizontalLayout_5.addWidget(self.dsb_unlabellwr)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_13 = QtWidgets.QLabel(self.tab_plots)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.sb_linethick = QtWidgets.QSpinBox(self.tab_plots)
        self.sb_linethick.setEnabled(False)
        self.sb_linethick.setObjectName("sb_linethick")
        self.horizontalLayout_4.addWidget(self.sb_linethick)
        self.label_6 = QtWidgets.QLabel(self.tab_plots)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.hl_2 = QtWidgets.QHBoxLayout()
        self.hl_2.setObjectName("hl_2")
        self.lbl_background = QtWidgets.QLabel(self.tab_plots)
        self.lbl_background.setObjectName("lbl_background")
        self.hl_2.addWidget(self.lbl_background)
        self.cb_background = QtWidgets.QComboBox(self.tab_plots)
        self.cb_background.setEnabled(False)
        self.cb_background.setObjectName("cb_background")
        self.cb_background.addItem("")
        self.cb_background.addItem("")
        self.cb_background.addItem("")
        self.cb_background.addItem("")
        self.cb_background.addItem("")
        self.cb_background.addItem("")
        self.cb_background.addItem("")
        self.cb_background.addItem("")
        self.cb_background.addItem("")
        self.hl_2.addWidget(self.cb_background)
        self.verticalLayout_3.addLayout(self.hl_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.tab_plots)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.cb_line_style = QtWidgets.QComboBox(self.tab_plots)
        self.cb_line_style.setEnabled(False)
        self.cb_line_style.setObjectName("cb_line_style")
        self.horizontalLayout.addWidget(self.cb_line_style)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_16 = QtWidgets.QLabel(self.tab_plots)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_6.addWidget(self.label_16)
        self.cb_color_scheme = QtWidgets.QComboBox(self.tab_plots)
        self.cb_color_scheme.setEnabled(False)
        self.cb_color_scheme.setObjectName("cb_color_scheme")
        self.horizontalLayout_6.addWidget(self.cb_color_scheme)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_17 = QtWidgets.QLabel(self.tab_plots)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        self.sb_error_style = QtWidgets.QComboBox(self.tab_plots)
        self.sb_error_style.setEnabled(False)
        self.sb_error_style.setObjectName("sb_error_style")
        self.horizontalLayout_7.addWidget(self.sb_error_style)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.groupBox = QtWidgets.QGroupBox(self.tab_plots)
        self.groupBox.setEnabled(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_3.setEnabled(False)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout.addWidget(self.spinBox_3, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 2, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_4.setEnabled(False)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout.addWidget(self.spinBox_4, 0, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 4, 1, 1)
        self.spinBox_5 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_5.setEnabled(False)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout.addWidget(self.spinBox_5, 0, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.spinBox_6 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_6.setEnabled(False)
        self.spinBox_6.setObjectName("spinBox_6")
        self.gridLayout.addWidget(self.spinBox_6, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 2, 1, 1)
        self.spinBox_7 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_7.setEnabled(False)
        self.spinBox_7.setObjectName("spinBox_7")
        self.gridLayout.addWidget(self.spinBox_7, 1, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 4, 1, 1)
        self.spinBox_8 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_8.setEnabled(False)
        self.spinBox_8.setObjectName("spinBox_8")
        self.gridLayout.addWidget(self.spinBox_8, 1, 5, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_plots, "")
        self.tab_fitting = QtWidgets.QWidget()
        self.tab_fitting.setObjectName("tab_fitting")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_fitting)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_24 = QtWidgets.QLabel(self.tab_fitting)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_2.addWidget(self.label_24)
        self.cb_fittingvar = QtWidgets.QComboBox(self.tab_fitting)
        self.cb_fittingvar.setEnabled(False)
        self.cb_fittingvar.setObjectName("cb_fittingvar")
        self.cb_fittingvar.addItem("")
        self.cb_fittingvar.addItem("")
        self.horizontalLayout_2.addWidget(self.cb_fittingvar)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_25 = QtWidgets.QLabel(self.tab_fitting)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_3.addWidget(self.label_25)
        self.cb_fittingseq = QtWidgets.QComboBox(self.tab_fitting)
        self.cb_fittingseq.setEnabled(False)
        self.cb_fittingseq.setObjectName("cb_fittingseq")
        self.cb_fittingseq.addItem("")
        self.cb_fittingseq.addItem("")
        self.horizontalLayout_3.addWidget(self.cb_fittingseq)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.gb_coarseoptions = QtWidgets.QGroupBox(self.tab_fitting)
        self.gb_coarseoptions.setObjectName("gb_coarseoptions")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gb_coarseoptions)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.gb_coarseoptions)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.le_coarsetolc = QtWidgets.QLineEdit(self.gb_coarseoptions)
        self.le_coarsetolc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_coarsetolc.setObjectName("le_coarsetolc")
        self.gridLayout_3.addWidget(self.le_coarsetolc, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gb_coarseoptions)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 1, 0, 1, 1)
        self.le_coarsetolv = QtWidgets.QLineEdit(self.gb_coarseoptions)
        self.le_coarsetolv.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_coarsetolv.setObjectName("le_coarsetolv")
        self.gridLayout_3.addWidget(self.le_coarsetolv, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gb_coarseoptions)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 2, 0, 1, 1)
        self.sb_coarsemaxits = QtWidgets.QSpinBox(self.gb_coarseoptions)
        self.sb_coarsemaxits.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sb_coarsemaxits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_coarsemaxits.setMaximum(999)
        self.sb_coarsemaxits.setProperty("value", 10)
        self.sb_coarsemaxits.setObjectName("sb_coarsemaxits")
        self.gridLayout_3.addWidget(self.sb_coarsemaxits, 2, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.verticalLayout_7.addWidget(self.gb_coarseoptions)
        self.gb_fineoptions = QtWidgets.QGroupBox(self.tab_fitting)
        self.gb_fineoptions.setObjectName("gb_fineoptions")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gb_fineoptions)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.gb_fineoptions)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.le_finetolc = QtWidgets.QLineEdit(self.gb_fineoptions)
        self.le_finetolc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_finetolc.setObjectName("le_finetolc")
        self.gridLayout_4.addWidget(self.le_finetolc, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gb_fineoptions)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 1, 0, 1, 1)
        self.le_finetolv = QtWidgets.QLineEdit(self.gb_fineoptions)
        self.le_finetolv.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_finetolv.setObjectName("le_finetolv")
        self.gridLayout_4.addWidget(self.le_finetolv, 1, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gb_fineoptions)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 2, 0, 1, 1)
        self.sb_finemaxits = QtWidgets.QSpinBox(self.gb_fineoptions)
        self.sb_finemaxits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_finemaxits.setMaximum(999)
        self.sb_finemaxits.setProperty("value", 50)
        self.sb_finemaxits.setObjectName("sb_finemaxits")
        self.gridLayout_4.addWidget(self.sb_finemaxits, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.verticalLayout_7.addWidget(self.gb_fineoptions)
        self.tabWidget.addTab(self.tab_fitting, "")
        self.tab_conc = QtWidgets.QWidget()
        self.tab_conc.setEnabled(True)
        self.tab_conc.setObjectName("tab_conc")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_conc)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_18 = QtWidgets.QLabel(self.tab_conc)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_8.addWidget(self.label_18)
        self.cb_engine = QtWidgets.QComboBox(self.tab_conc)
        self.cb_engine.setObjectName("cb_engine")
        self.cb_engine.addItem("")
        self.cb_engine.addItem("")
        self.horizontalLayout_8.addWidget(self.cb_engine)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_52 = QtWidgets.QLabel(self.tab_conc)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_19.addWidget(self.label_52)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_conc)
        self.lineEdit_9.setEnabled(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_19.addWidget(self.lineEdit_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_53 = QtWidgets.QLabel(self.tab_conc)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_20.addWidget(self.label_53)
        self.spinBox = QtWidgets.QSpinBox(self.tab_conc)
        self.spinBox.setEnabled(False)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_20.addWidget(self.spinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_23 = QtWidgets.QLabel(self.tab_conc)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_21.addWidget(self.label_23)
        self.cb_interp = QtWidgets.QComboBox(self.tab_conc)
        self.cb_interp.setEnabled(False)
        self.cb_interp.setObjectName("cb_interp")
        self.cb_interp.addItem("")
        self.cb_interp.addItem("")
        self.cb_interp.addItem("")
        self.cb_interp.addItem("")
        self.cb_interp.addItem("")
        self.horizontalLayout_21.addWidget(self.cb_interp)
        self.verticalLayout_2.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_51 = QtWidgets.QLabel(self.tab_conc)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_22.addWidget(self.label_51)
        self.cb_forcer = QtWidgets.QComboBox(self.tab_conc)
        self.cb_forcer.setEnabled(False)
        self.cb_forcer.setObjectName("cb_forcer")
        self.cb_forcer.addItem("")
        self.cb_forcer.addItem("")
        self.cb_forcer.addItem("")
        self.cb_forcer.addItem("")
        self.horizontalLayout_22.addWidget(self.cb_forcer)
        self.verticalLayout_2.addLayout(self.horizontalLayout_22)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cb_stepwise = QtWidgets.QCheckBox(self.tab_conc)
        self.cb_stepwise.setObjectName("cb_stepwise")
        self.gridLayout_2.addWidget(self.cb_stepwise, 2, 0, 1, 1)
        self.cb_steplim = QtWidgets.QCheckBox(self.tab_conc)
        self.cb_steplim.setChecked(True)
        self.cb_steplim.setObjectName("cb_steplim")
        self.gridLayout_2.addWidget(self.cb_steplim, 1, 0, 1, 1)
        self.cb_damping = QtWidgets.QCheckBox(self.tab_conc)
        self.cb_damping.setObjectName("cb_damping")
        self.gridLayout_2.addWidget(self.cb_damping, 0, 0, 1, 1)
        self.cb_scaling = QtWidgets.QCheckBox(self.tab_conc)
        self.cb_scaling.setObjectName("cb_scaling")
        self.gridLayout_2.addWidget(self.cb_scaling, 0, 1, 1, 1)
        self.cb_estimate = QtWidgets.QCheckBox(self.tab_conc)
        self.cb_estimate.setChecked(True)
        self.cb_estimate.setObjectName("cb_estimate")
        self.gridLayout_2.addWidget(self.cb_estimate, 1, 1, 1, 1)
        self.cb_zeroffd = QtWidgets.QCheckBox(self.tab_conc)
        self.cb_zeroffd.setObjectName("cb_zeroffd")
        self.gridLayout_2.addWidget(self.cb_zeroffd, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.label_19 = QtWidgets.QLabel(self.tab_conc)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab_conc, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.hl_1 = QtWidgets.QHBoxLayout()
        self.hl_1.setObjectName("hl_1")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_1.addItem(spacerItem3)
        self.buttonBox = QtWidgets.QDialogButtonBox(ApesOptions)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.hl_1.addWidget(self.buttonBox)
        self.verticalLayout_4.addLayout(self.hl_1)

        self.retranslateUi(ApesOptions)
        self.tabWidget.setCurrentIndex(1)
        self.cb_verbosity.setCurrentIndex(0)
        self.cb_engine.setCurrentIndex(1)
        self.buttonBox.accepted.connect(ApesOptions.accept)
        self.buttonBox.rejected.connect(ApesOptions.reject)
        QtCore.QMetaObject.connectSlotsByName(ApesOptions)

    def retranslateUi(self, ApesOptions):
        _translate = QtCore.QCoreApplication.translate
        ApesOptions.setWindowTitle(_translate("ApesOptions", "Dialog"))
        self.lbl_verbosity.setText(_translate("ApesOptions", "Output verbosity"))
        self.cb_verbosity.setItemText(0, _translate("ApesOptions", "Minimal"))
        self.cb_verbosity.setItemText(1, _translate("ApesOptions", "Regular"))
        self.cb_verbosity.setItemText(2, _translate("ApesOptions", "Full"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_general), _translate("ApesOptions", "General"))
        self.label.setText(_translate("ApesOptions", "Ignore lower than"))
        self.dsb_ignorelwr.setSuffix(_translate("ApesOptions", "%"))
        self.label_2.setText(_translate("ApesOptions", "Unlabel lower than"))
        self.dsb_unlabellwr.setSuffix(_translate("ApesOptions", "%"))
        self.label_13.setText(_translate("ApesOptions", "Line thickness"))
        self.label_6.setText(_translate("ApesOptions", "pts"))
        self.lbl_background.setText(_translate("ApesOptions", "Background color"))
        self.cb_background.setItemText(0, _translate("ApesOptions", "Transparent (white)"))
        self.cb_background.setItemText(1, _translate("ApesOptions", "Blue"))
        self.cb_background.setItemText(2, _translate("ApesOptions", "Green"))
        self.cb_background.setItemText(3, _translate("ApesOptions", "Red"))
        self.cb_background.setItemText(4, _translate("ApesOptions", "Cyan"))
        self.cb_background.setItemText(5, _translate("ApesOptions", "Magenta"))
        self.cb_background.setItemText(6, _translate("ApesOptions", "Yellow"))
        self.cb_background.setItemText(7, _translate("ApesOptions", "Black"))
        self.cb_background.setItemText(8, _translate("ApesOptions", "White"))
        self.label_3.setText(_translate("ApesOptions", "Line style"))
        self.label_16.setText(_translate("ApesOptions", "Color scheme"))
        self.label_17.setText(_translate("ApesOptions", "Error style"))
        self.groupBox.setTitle(_translate("ApesOptions", "Plot Margins"))
        self.label_7.setText(_translate("ApesOptions", "left"))
        self.label_8.setText(_translate("ApesOptions", "right"))
        self.label_11.setText(_translate("ApesOptions", "wspace"))
        self.label_9.setText(_translate("ApesOptions", "top"))
        self.label_10.setText(_translate("ApesOptions", "bottom"))
        self.label_12.setText(_translate("ApesOptions", "hspace"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_plots), _translate("ApesOptions", "Plots"))
        self.label_24.setText(_translate("ApesOptions", "Fitting Variable"))
        self.cb_fittingvar.setItemText(0, _translate("ApesOptions", "Beta logarithm"))
        self.cb_fittingvar.setItemText(1, _translate("ApesOptions", "Beta"))
        self.label_25.setText(_translate("ApesOptions", "Fitting Sequence"))
        self.cb_fittingseq.setItemText(0, _translate("ApesOptions", "Best fit for all constants"))
        self.cb_fittingseq.setItemText(1, _translate("ApesOptions", "Remove worst beta in turn"))
        self.gb_coarseoptions.setTitle(_translate("ApesOptions", "Coarse Fitting Criteria Options"))
        self.label_4.setText(_translate("ApesOptions", "Threshold for χ²"))
        self.le_coarsetolc.setText(_translate("ApesOptions", "1.0e-5"))
        self.label_15.setText(_translate("ApesOptions", "Threshold for vars"))
        self.le_coarsetolv.setText(_translate("ApesOptions", "1.0e-2"))
        self.label_22.setText(_translate("ApesOptions", "Max. iterations"))
        self.gb_fineoptions.setTitle(_translate("ApesOptions", "Fine Fitting Criteria Options"))
        self.label_5.setText(_translate("ApesOptions", "Threshold for χ²"))
        self.le_finetolc.setText(_translate("ApesOptions", "1.0e-15"))
        self.label_14.setText(_translate("ApesOptions", "Threshold for vars"))
        self.le_finetolv.setText(_translate("ApesOptions", "1.0e-5"))
        self.label_26.setText(_translate("ApesOptions", "Max. iterations"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_fitting), _translate("ApesOptions", "Fitting"))
        self.label_18.setText(_translate("ApesOptions", "Engine:"))
        self.cb_engine.setItemText(0, _translate("ApesOptions", "Python"))
        self.cb_engine.setItemText(1, _translate("ApesOptions", "Fortran"))
        self.label_52.setText(_translate("ApesOptions", "Convergence Threshold"))
        self.label_53.setText(_translate("ApesOptions", "Max.Iterations"))
        self.label_23.setText(_translate("ApesOptions", "Interpolation"))
        self.cb_interp.setItemText(0, _translate("ApesOptions", "Auto"))
        self.cb_interp.setItemText(1, _translate("ApesOptions", "None"))
        self.cb_interp.setItemText(2, _translate("ApesOptions", "Linear"))
        self.cb_interp.setItemText(3, _translate("ApesOptions", "Quadratic "))
        self.cb_interp.setItemText(4, _translate("ApesOptions", "Cubic"))
        self.label_51.setText(_translate("ApesOptions", "Forcer"))
        self.cb_forcer.setItemText(0, _translate("ApesOptions", "None"))
        self.cb_forcer.setItemText(1, _translate("ApesOptions", "Est"))
        self.cb_forcer.setItemText(2, _translate("ApesOptions", "Cubic"))
        self.cb_forcer.setItemText(3, _translate("ApesOptions", "Equil"))
        self.cb_stepwise.setText(_translate("ApesOptions", "Stepwise fitting"))
        self.cb_steplim.setText(_translate("ApesOptions", "Step limiter"))
        self.cb_damping.setText(_translate("ApesOptions", "Damping"))
        self.cb_scaling.setText(_translate("ApesOptions", "Scaling"))
        self.cb_estimate.setText(_translate("ApesOptions", "Estimate initial guess"))
        self.cb_zeroffd.setText(_translate("ApesOptions", "Zero off-diag"))
        self.label_19.setText(_translate("ApesOptions", "Warning: Do not change these options unless you know what you are doing."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_conc), _translate("ApesOptions", "Conc."))
