# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/qsi.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QSi_Window(object):
    def setupUi(self, QSi_Window):
        QSi_Window.setObjectName("QSi_Window")
        QSi_Window.resize(938, 677)
        self.centralwidget = QtWidgets.QWidget(QSi_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.splitter_data = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_data.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_data.setObjectName("splitter_data")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_data)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(180, 60))
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.rb_distri = QtWidgets.QRadioButton(self.groupBox)
        self.rb_distri.setEnabled(True)
        self.rb_distri.setGeometry(QtCore.QRect(0, 20, 163, 22))
        self.rb_distri.setChecked(True)
        self.rb_distri.setObjectName("rb_distri")
        self.rb_simu = QtWidgets.QRadioButton(self.groupBox)
        self.rb_simu.setGeometry(QtCore.QRect(0, 40, 163, 22))
        self.rb_simu.setObjectName("rb_simu")
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.cb_Xaxis = QtWidgets.QComboBox(self.layoutWidget)
        self.cb_Xaxis.setObjectName("cb_Xaxis")
        self.horizontalLayout_4.addWidget(self.cb_Xaxis)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.cb_Yaxis = QtWidgets.QComboBox(self.layoutWidget)
        self.cb_Yaxis.setObjectName("cb_Yaxis")
        self.horizontalLayout_5.addWidget(self.cb_Yaxis)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.sb_NPoints = QtWidgets.QSpinBox(self.layoutWidget)
        self.sb_NPoints.setMinimum(10)
        self.sb_NPoints.setMaximum(500)
        self.sb_NPoints.setProperty("value", 50)
        self.sb_NPoints.setObjectName("sb_NPoints")
        self.horizontalLayout_2.addWidget(self.sb_NPoints)
        self.cbPlotErrors = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbPlotErrors.setEnabled(True)
        self.cbPlotErrors.setObjectName("cbPlotErrors")
        self.horizontalLayout_2.addWidget(self.cbPlotErrors)
        self.sbError = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.sbError.setEnabled(True)
        self.sbError.setMaximum(100.0)
        self.sbError.setProperty("value", 95.0)
        self.sbError.setObjectName("sbError")
        self.horizontalLayout_2.addWidget(self.sbError)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.splitter = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.stackedWidget = QtWidgets.QStackedWidget(self.splitter)
        self.stackedWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_simu = QtWidgets.QWidget()
        self.page_simu.setObjectName("page_simu")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_simu)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.table_species = QtWidgets.QTableWidget(self.page_simu)
        self.table_species.setObjectName("table_species")
        self.table_species.setColumnCount(4)
        self.table_species.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.table_species.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_species.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_species.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_species.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_species.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_species.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_species.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_species.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_species.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_species.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_species.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_species.setItem(1, 2, item)
        self.table_species.verticalHeader().setVisible(False)
        self.table_species.verticalHeader().setCascadingSectionResizes(True)
        self.horizontalLayout_3.addWidget(self.table_species)
        self.stackedWidget.addWidget(self.page_simu)
        self.page_titr = QtWidgets.QWidget()
        self.page_titr.setObjectName("page_titr")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_titr)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.table_titration = QtWidgets.QTableWidget(self.page_titr)
        self.table_titration.setObjectName("table_titration")
        self.table_titration.setColumnCount(3)
        self.table_titration.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(1, 2, item)
        self.table_titration.verticalHeader().setVisible(False)
        self.table_titration.verticalHeader().setCascadingSectionResizes(True)
        self.verticalLayout_5.addWidget(self.table_titration)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.page_titr)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.page_titr)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.page_titr)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.dsb_V0 = QtWidgets.QDoubleSpinBox(self.page_titr)
        self.dsb_V0.setProperty("value", 10.0)
        self.dsb_V0.setObjectName("dsb_V0")
        self.gridLayout.addWidget(self.dsb_V0, 1, 1, 1, 1)
        self.dsb_Vf = QtWidgets.QDoubleSpinBox(self.page_titr)
        self.dsb_Vf.setProperty("value", 11.0)
        self.dsb_Vf.setObjectName("dsb_Vf")
        self.gridLayout.addWidget(self.dsb_Vf, 1, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.stackedWidget.addWidget(self.page_titr)
        self.table_model = QtWidgets.QTableWidget(self.splitter)
        self.table_model.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_model.setCornerButtonEnabled(False)
        self.table_model.setObjectName("table_model")
        self.table_model.setColumnCount(3)
        self.table_model.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.table_model.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_model.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_model.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_model.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_model.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_model.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_model.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_model.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_model.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_model.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_model.setItem(1, 2, item)
        self.table_model.verticalHeader().setVisible(False)
        self.table_model.verticalHeader().setCascadingSectionResizes(True)
        self.table_model.verticalHeader().setHighlightSections(True)
        self.verticalLayout_3.addWidget(self.splitter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_addbeta = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_addbeta.setObjectName("pb_addbeta")
        self.horizontalLayout.addWidget(self.pb_addbeta)
        self.pb_removebeta = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_removebeta.setObjectName("pb_removebeta")
        self.horizontalLayout.addWidget(self.pb_removebeta)
        self.pb_addreag = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_addreag.setObjectName("pb_addreag")
        self.horizontalLayout.addWidget(self.pb_addreag)
        self.pb_removereag = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_removereag.setObjectName("pb_removereag")
        self.horizontalLayout.addWidget(self.pb_removereag)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.pb_go = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_go.setObjectName("pb_go")
        self.horizontalLayout_6.addWidget(self.pb_go)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_data)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_plot = QtWidgets.QWidget(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_plot.sizePolicy().hasHeightForWidth())
        self.widget_plot.setSizePolicy(sizePolicy)
        self.widget_plot.setSizeIncrement(QtCore.QSize(1, 1))
        self.widget_plot.setObjectName("widget_plot")
        self.verticalLayout_4.addWidget(self.widget_plot)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.dsb_ignorelowerthan = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.dsb_ignorelowerthan.setObjectName("dsb_ignorelowerthan")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dsb_ignorelowerthan)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.dsb_unlabellowerthan = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.dsb_unlabellowerthan.setObjectName("dsb_unlabellowerthan")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dsb_unlabellowerthan)
        self.verticalLayout_4.addLayout(self.formLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_8.addWidget(self.splitter_data)
        QSi_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(QSi_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 938, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuPlot = QtWidgets.QMenu(self.menubar)
        self.menuPlot.setEnabled(False)
        self.menuPlot.setObjectName("menuPlot")
        QSi_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(QSi_Window)
        self.statusbar.setObjectName("statusbar")
        QSi_Window.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(QSi_Window)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(QSi_Window)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(QSi_Window)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(QSi_Window)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionExit = QtWidgets.QAction(QSi_Window)
        self.actionExit.setObjectName("actionExit")
        self.actionPlot_unplot = QtWidgets.QAction(QSi_Window)
        self.actionPlot_unplot.setEnabled(False)
        self.actionPlot_unplot.setObjectName("actionPlot_unplot")
        self.actionAddittional_data = QtWidgets.QAction(QSi_Window)
        self.actionAddittional_data.setObjectName("actionAddittional_data")
        self.actionExport_Graph = QtWidgets.QAction(QSi_Window)
        self.actionExport_Graph.setObjectName("actionExport_Graph")
        self.actionExport_Data = QtWidgets.QAction(QSi_Window)
        self.actionExport_Data.setObjectName("actionExport_Data")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_Graph)
        self.menuFile.addAction(self.actionExport_Data)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuPlot.addAction(self.actionPlot_unplot)
        self.menuPlot.addAction(self.actionAddittional_data)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPlot.menuAction())

        self.retranslateUi(QSi_Window)
        self.stackedWidget.setCurrentIndex(1)
        self.actionExit.activated.connect(QSi_Window.close)
        QtCore.QMetaObject.connectSlotsByName(QSi_Window)

    def retranslateUi(self, QSi_Window):
        _translate = QtCore.QCoreApplication.translate
        QSi_Window.setWindowTitle(_translate("QSi_Window", "MainWindow"))
        self.groupBox.setTitle(_translate("QSi_Window", "Type of  Graphic"))
        self.rb_distri.setText(_translate("QSi_Window", "Species Distribution"))
        self.rb_simu.setText(_translate("QSi_Window", "Titration Simulation"))
        self.label.setText(_translate("QSi_Window", "X-axis"))
        self.label_2.setText(_translate("QSi_Window", "Y-axis"))
        self.label_8.setText(_translate("QSi_Window", "Points"))
        self.cbPlotErrors.setText(_translate("QSi_Window", "plot errors at"))
        self.sbError.setSuffix(_translate("QSi_Window", "%"))
        item = self.table_species.verticalHeaderItem(0)
        item.setText(_translate("QSi_Window", "1"))
        item = self.table_species.verticalHeaderItem(1)
        item.setText(_translate("QSi_Window", "2"))
        item = self.table_species.horizontalHeaderItem(0)
        item.setText(_translate("QSi_Window", "Label"))
        item = self.table_species.horizontalHeaderItem(1)
        item.setText(_translate("QSi_Window", "Initial Titre"))
        item = self.table_species.horizontalHeaderItem(2)
        item.setText(_translate("QSi_Window", "Final Titre"))
        item = self.table_species.horizontalHeaderItem(3)
        item.setText(_translate("QSi_Window", "pX?"))
        __sortingEnabled = self.table_species.isSortingEnabled()
        self.table_species.setSortingEnabled(False)
        item = self.table_species.item(0, 0)
        item.setText(_translate("QSi_Window", "L"))
        item = self.table_species.item(0, 1)
        item.setText(_translate("QSi_Window", "0.1"))
        item = self.table_species.item(0, 2)
        item.setText(_translate("QSi_Window", "0.1"))
        item = self.table_species.item(1, 0)
        item.setText(_translate("QSi_Window", "H"))
        item = self.table_species.item(1, 1)
        item.setText(_translate("QSi_Window", "2"))
        item = self.table_species.item(1, 2)
        item.setText(_translate("QSi_Window", "12"))
        self.table_species.setSortingEnabled(__sortingEnabled)
        item = self.table_titration.verticalHeaderItem(0)
        item.setText(_translate("QSi_Window", "1"))
        item = self.table_titration.verticalHeaderItem(1)
        item.setText(_translate("QSi_Window", "2"))
        item = self.table_titration.horizontalHeaderItem(0)
        item.setText(_translate("QSi_Window", "Label"))
        item = self.table_titration.horizontalHeaderItem(1)
        item.setText(_translate("QSi_Window", "Initial"))
        item = self.table_titration.horizontalHeaderItem(2)
        item.setText(_translate("QSi_Window", "Buret"))
        __sortingEnabled = self.table_titration.isSortingEnabled()
        self.table_titration.setSortingEnabled(False)
        item = self.table_titration.item(0, 0)
        item.setText(_translate("QSi_Window", "L"))
        item = self.table_titration.item(0, 1)
        item.setText(_translate("QSi_Window", "10.0"))
        item = self.table_titration.item(0, 2)
        item.setText(_translate("QSi_Window", "0"))
        item = self.table_titration.item(1, 0)
        item.setText(_translate("QSi_Window", "H"))
        item = self.table_titration.item(1, 1)
        item.setText(_translate("QSi_Window", "20.0"))
        item = self.table_titration.item(1, 2)
        item.setText(_translate("QSi_Window", "-0.1"))
        self.table_titration.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("QSi_Window", "Initial"))
        self.label_5.setText(_translate("QSi_Window", "Final"))
        self.label_3.setText(_translate("QSi_Window", "Volume"))
        self.table_model.setToolTip(_translate("QSi_Window", "<html><head/><body><p>Constants must be a float number representing the constant in log10 units in the format 12.13(4) where the number in parenthesis is optional and represents the error.</p></body></html>"))
        item = self.table_model.verticalHeaderItem(0)
        item.setText(_translate("QSi_Window", "1"))
        item = self.table_model.verticalHeaderItem(1)
        item.setText(_translate("QSi_Window", "2"))
        item = self.table_model.horizontalHeaderItem(0)
        item.setText(_translate("QSi_Window", "constant"))
        item = self.table_model.horizontalHeaderItem(1)
        item.setText(_translate("QSi_Window", "L"))
        item = self.table_model.horizontalHeaderItem(2)
        item.setText(_translate("QSi_Window", "H"))
        __sortingEnabled = self.table_model.isSortingEnabled()
        self.table_model.setSortingEnabled(False)
        item = self.table_model.item(0, 0)
        item.setText(_translate("QSi_Window", "8.08"))
        item = self.table_model.item(0, 1)
        item.setText(_translate("QSi_Window", "1"))
        item = self.table_model.item(0, 2)
        item.setText(_translate("QSi_Window", "1"))
        item = self.table_model.item(1, 0)
        item.setText(_translate("QSi_Window", "-13.73"))
        item = self.table_model.item(1, 1)
        item.setText(_translate("QSi_Window", "0"))
        item = self.table_model.item(1, 2)
        item.setText(_translate("QSi_Window", "-1"))
        self.table_model.setSortingEnabled(__sortingEnabled)
        self.pb_addbeta.setText(_translate("QSi_Window", "Add ß"))
        self.pb_removebeta.setText(_translate("QSi_Window", "Remove ß"))
        self.pb_addreag.setText(_translate("QSi_Window", "Add reagent"))
        self.pb_removereag.setText(_translate("QSi_Window", "Remove reagent"))
        self.pb_go.setText(_translate("QSi_Window", "Go!"))
        self.label_6.setText(_translate("QSi_Window", "Ignore lower than:"))
        self.label_7.setText(_translate("QSi_Window", "Unlabel lower than:"))
        self.menuFile.setTitle(_translate("QSi_Window", "File"))
        self.menuPlot.setTitle(_translate("QSi_Window", "Plot"))
        self.actionNew.setText(_translate("QSi_Window", "New"))
        self.actionOpen.setText(_translate("QSi_Window", "Open"))
        self.actionSave.setText(_translate("QSi_Window", "Save"))
        self.actionSave_as.setText(_translate("QSi_Window", "Save as"))
        self.actionExit.setText(_translate("QSi_Window", "Exit"))
        self.actionPlot_unplot.setText(_translate("QSi_Window", "Plot/unplot"))
        self.actionAddittional_data.setText(_translate("QSi_Window", "Addittional data"))
        self.actionExport_Graph.setText(_translate("QSi_Window", "Export Graph"))
        self.actionExport_Data.setText(_translate("QSi_Window", "Export Data"))

