# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/sdistri.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpeciationWidget(object):
    def setupUi(self, SpeciationWidget):
        SpeciationWidget.setObjectName("SpeciationWidget")
        SpeciationWidget.resize(348, 222)
        self.verticalLayout = QtWidgets.QVBoxLayout(SpeciationWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hl_1 = QtWidgets.QHBoxLayout()
        self.hl_1.setObjectName("hl_1")
        self.lbl_xaxis = QtWidgets.QLabel(SpeciationWidget)
        self.lbl_xaxis.setObjectName("lbl_xaxis")
        self.hl_1.addWidget(self.lbl_xaxis)
        self.cb_Xaxis = QtWidgets.QComboBox(SpeciationWidget)
        self.cb_Xaxis.setObjectName("cb_Xaxis")
        self.hl_1.addWidget(self.cb_Xaxis)
        self.lbl_yaxis = QtWidgets.QLabel(SpeciationWidget)
        self.lbl_yaxis.setObjectName("lbl_yaxis")
        self.hl_1.addWidget(self.lbl_yaxis)
        self.cb_Yaxis = QtWidgets.QComboBox(SpeciationWidget)
        self.cb_Yaxis.setObjectName("cb_Yaxis")
        self.hl_1.addWidget(self.cb_Yaxis)
        self.verticalLayout.addLayout(self.hl_1)
        self.hl_2 = QtWidgets.QHBoxLayout()
        self.hl_2.setObjectName("hl_2")
        self.lbl_points = QtWidgets.QLabel(SpeciationWidget)
        self.lbl_points.setObjectName("lbl_points")
        self.hl_2.addWidget(self.lbl_points)
        self.sb_NPoints = QtWidgets.QSpinBox(SpeciationWidget)
        self.sb_NPoints.setMinimum(10)
        self.sb_NPoints.setMaximum(500)
        self.sb_NPoints.setProperty("value", 100)
        self.sb_NPoints.setObjectName("sb_NPoints")
        self.hl_2.addWidget(self.sb_NPoints)
        self.cbPlotErrors = QtWidgets.QCheckBox(SpeciationWidget)
        self.cbPlotErrors.setEnabled(True)
        self.cbPlotErrors.setObjectName("cbPlotErrors")
        self.hl_2.addWidget(self.cbPlotErrors)
        self.sbError = QtWidgets.QDoubleSpinBox(SpeciationWidget)
        self.sbError.setEnabled(True)
        self.sbError.setMaximum(100.0)
        self.sbError.setProperty("value", 95.0)
        self.sbError.setObjectName("sbError")
        self.hl_2.addWidget(self.sbError)
        self.verticalLayout.addLayout(self.hl_2)
        self.table_species = QtWidgets.QTableWidget(SpeciationWidget)
        self.table_species.setObjectName("table_species")
        self.table_species.setColumnCount(4)
        self.table_species.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.table_species.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_species.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_species.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_species.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_species.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_species.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_species.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_species.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_species.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_species.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_species.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_species.setItem(1, 2, item)
        self.table_species.horizontalHeader().setDefaultSectionSize(70)
        self.table_species.verticalHeader().setVisible(False)
        self.table_species.verticalHeader().setCascadingSectionResizes(True)
        self.verticalLayout.addWidget(self.table_species)

        self.retranslateUi(SpeciationWidget)
        QtCore.QMetaObject.connectSlotsByName(SpeciationWidget)

    def retranslateUi(self, SpeciationWidget):
        _translate = QtCore.QCoreApplication.translate
        SpeciationWidget.setWindowTitle(_translate("SpeciationWidget", "Form"))
        self.lbl_xaxis.setText(_translate("SpeciationWidget", "X-axis"))
        self.lbl_yaxis.setText(_translate("SpeciationWidget", "Y-axis"))
        self.lbl_points.setText(_translate("SpeciationWidget", "Points"))
        self.cbPlotErrors.setText(_translate("SpeciationWidget", "plot errors at"))
        self.sbError.setSuffix(_translate("SpeciationWidget", "%"))
        item = self.table_species.verticalHeaderItem(0)
        item.setText(_translate("SpeciationWidget", "1"))
        item = self.table_species.verticalHeaderItem(1)
        item.setText(_translate("SpeciationWidget", "2"))
        item = self.table_species.horizontalHeaderItem(0)
        item.setText(_translate("SpeciationWidget", "Label"))
        item = self.table_species.horizontalHeaderItem(1)
        item.setText(_translate("SpeciationWidget", "Initial Titre"))
        item = self.table_species.horizontalHeaderItem(2)
        item.setText(_translate("SpeciationWidget", "Final Titre"))
        item = self.table_species.horizontalHeaderItem(3)
        item.setText(_translate("SpeciationWidget", "pX?"))
        __sortingEnabled = self.table_species.isSortingEnabled()
        self.table_species.setSortingEnabled(False)
        item = self.table_species.item(0, 0)
        item.setText(_translate("SpeciationWidget", "L"))
        item = self.table_species.item(0, 1)
        item.setText(_translate("SpeciationWidget", "0.1"))
        item = self.table_species.item(0, 2)
        item.setText(_translate("SpeciationWidget", "0.1"))
        item = self.table_species.item(1, 0)
        item.setText(_translate("SpeciationWidget", "H"))
        item = self.table_species.item(1, 1)
        item.setText(_translate("SpeciationWidget", "2"))
        item = self.table_species.item(1, 2)
        item.setText(_translate("SpeciationWidget", "12"))
        self.table_species.setSortingEnabled(__sortingEnabled)
