# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/specds.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpecDSWidget(object):
    def setupUi(self, SpecDSWidget):
        SpecDSWidget.setObjectName("SpecDSWidget")
        SpecDSWidget.resize(655, 440)
        self.verticalLayout = QtWidgets.QVBoxLayout(SpecDSWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.le_title = QtWidgets.QLineEdit(SpecDSWidget)
        self.le_title.setObjectName("le_title")
        self.horizontalLayout.addWidget(self.le_title)
        self.label_2 = QtWidgets.QLabel(SpecDSWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.dsb_path = QtWidgets.QDoubleSpinBox(SpecDSWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsb_path.sizePolicy().hasHeightForWidth())
        self.dsb_path.setSizePolicy(sizePolicy)
        self.dsb_path.setToolTip("")
        self.dsb_path.setFrame(True)
        self.dsb_path.setPrefix("")
        self.dsb_path.setProperty("value", 1.0)
        self.dsb_path.setObjectName("dsb_path")
        self.horizontalLayout.addWidget(self.dsb_path)
        self.label = QtWidgets.QLabel(SpecDSWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cb_titration = QtWidgets.QComboBox(SpecDSWidget)
        self.cb_titration.setObjectName("cb_titration")
        self.horizontalLayout.addWidget(self.cb_titration)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.table_data = QtWidgets.QTableWidget(SpecDSWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.table_data.sizePolicy().hasHeightForWidth())
        self.table_data.setSizePolicy(sizePolicy)
        self.table_data.setObjectName("table_data")
        self.table_data.setColumnCount(1)
        self.table_data.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.table_data.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_data.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_data.setItem(0, 0, item)
        self.table_data.horizontalHeader().setDefaultSectionSize(80)
        self.verticalLayout.addWidget(self.table_data)

        self.retranslateUi(SpecDSWidget)
        QtCore.QMetaObject.connectSlotsByName(SpecDSWidget)

    def retranslateUi(self, SpecDSWidget):
        _translate = QtCore.QCoreApplication.translate
        SpecDSWidget.setWindowTitle(_translate("SpecDSWidget", "Form"))
        self.label_2.setText(_translate("SpecDSWidget", "optical path"))
        self.dsb_path.setSuffix(_translate("SpecDSWidget", " cm"))
        self.label.setText(_translate("SpecDSWidget", "Titration"))
        item = self.table_data.verticalHeaderItem(0)
        item.setText(_translate("SpecDSWidget", "280"))
        item = self.table_data.horizontalHeaderItem(0)
        item.setText(_translate("SpecDSWidget", "1"))
        __sortingEnabled = self.table_data.isSortingEnabled()
        self.table_data.setSortingEnabled(False)
        item = self.table_data.item(0, 0)
        item.setText(_translate("SpecDSWidget", "0.00000"))
        self.table_data.setSortingEnabled(__sortingEnabled)
