# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/titrsimu.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TitrationWidget(object):
    def setupUi(self, TitrationWidget):
        TitrationWidget.setObjectName("TitrationWidget")
        TitrationWidget.resize(332, 259)
        self.verticalLayout = QtWidgets.QVBoxLayout(TitrationWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hl_1 = QtWidgets.QHBoxLayout()
        self.hl_1.setObjectName("hl_1")
        self.lbl_xaxis = QtWidgets.QLabel(TitrationWidget)
        self.lbl_xaxis.setObjectName("lbl_xaxis")
        self.hl_1.addWidget(self.lbl_xaxis)
        self.cb_Xaxis = QtWidgets.QComboBox(TitrationWidget)
        self.cb_Xaxis.setObjectName("cb_Xaxis")
        self.hl_1.addWidget(self.cb_Xaxis)
        self.lbl_yaxis = QtWidgets.QLabel(TitrationWidget)
        self.lbl_yaxis.setObjectName("lbl_yaxis")
        self.hl_1.addWidget(self.lbl_yaxis)
        self.cb_Yaxis = QtWidgets.QComboBox(TitrationWidget)
        self.cb_Yaxis.setObjectName("cb_Yaxis")
        self.hl_1.addWidget(self.cb_Yaxis)
        self.verticalLayout.addLayout(self.hl_1)
        self.hl_2 = QtWidgets.QHBoxLayout()
        self.hl_2.setObjectName("hl_2")
        self.lbl_points = QtWidgets.QLabel(TitrationWidget)
        self.lbl_points.setObjectName("lbl_points")
        self.hl_2.addWidget(self.lbl_points)
        self.sb_NPoints = QtWidgets.QSpinBox(TitrationWidget)
        self.sb_NPoints.setMinimum(10)
        self.sb_NPoints.setMaximum(1000)
        self.sb_NPoints.setSingleStep(5)
        self.sb_NPoints.setProperty("value", 100)
        self.sb_NPoints.setObjectName("sb_NPoints")
        self.hl_2.addWidget(self.sb_NPoints)
        self.cbPlotErrors = QtWidgets.QCheckBox(TitrationWidget)
        self.cbPlotErrors.setEnabled(True)
        self.cbPlotErrors.setObjectName("cbPlotErrors")
        self.hl_2.addWidget(self.cbPlotErrors)
        self.sbError = QtWidgets.QDoubleSpinBox(TitrationWidget)
        self.sbError.setEnabled(True)
        self.sbError.setMaximum(100.0)
        self.sbError.setProperty("value", 95.0)
        self.sbError.setObjectName("sbError")
        self.hl_2.addWidget(self.sbError)
        self.verticalLayout.addLayout(self.hl_2)
        self.table_titration = QtWidgets.QTableWidget(TitrationWidget)
        self.table_titration.setObjectName("table_titration")
        self.table_titration.setColumnCount(3)
        self.table_titration.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_titration.setItem(1, 2, item)
        self.table_titration.verticalHeader().setVisible(False)
        self.table_titration.verticalHeader().setCascadingSectionResizes(True)
        self.verticalLayout.addWidget(self.table_titration)
        self.gl_volume = QtWidgets.QGridLayout()
        self.gl_volume.setObjectName("gl_volume")
        self.lbl_Vi = QtWidgets.QLabel(TitrationWidget)
        self.lbl_Vi.setObjectName("lbl_Vi")
        self.gl_volume.addWidget(self.lbl_Vi, 0, 1, 1, 1)
        self.lbl_Vf = QtWidgets.QLabel(TitrationWidget)
        self.lbl_Vf.setObjectName("lbl_Vf")
        self.gl_volume.addWidget(self.lbl_Vf, 0, 2, 1, 1)
        self.lbl_V = QtWidgets.QLabel(TitrationWidget)
        self.lbl_V.setObjectName("lbl_V")
        self.gl_volume.addWidget(self.lbl_V, 1, 0, 1, 1)
        self.dsb_V0 = QtWidgets.QDoubleSpinBox(TitrationWidget)
        self.dsb_V0.setMaximum(1000.0)
        self.dsb_V0.setSingleStep(0.1)
        self.dsb_V0.setProperty("value", 10.0)
        self.dsb_V0.setObjectName("dsb_V0")
        self.gl_volume.addWidget(self.dsb_V0, 1, 1, 1, 1)
        self.dsb_Vf = QtWidgets.QDoubleSpinBox(TitrationWidget)
        self.dsb_Vf.setMaximum(1000.0)
        self.dsb_Vf.setSingleStep(0.1)
        self.dsb_Vf.setProperty("value", 11.0)
        self.dsb_Vf.setObjectName("dsb_Vf")
        self.gl_volume.addWidget(self.dsb_Vf, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gl_volume)

        self.retranslateUi(TitrationWidget)
        QtCore.QMetaObject.connectSlotsByName(TitrationWidget)

    def retranslateUi(self, TitrationWidget):
        _translate = QtCore.QCoreApplication.translate
        TitrationWidget.setWindowTitle(_translate("TitrationWidget", "Form"))
        self.lbl_xaxis.setText(_translate("TitrationWidget", "X-axis"))
        self.lbl_yaxis.setText(_translate("TitrationWidget", "Y-axis"))
        self.lbl_points.setText(_translate("TitrationWidget", "Points"))
        self.cbPlotErrors.setText(_translate("TitrationWidget", "plot errors at"))
        self.sbError.setSuffix(_translate("TitrationWidget", "%"))
        item = self.table_titration.verticalHeaderItem(0)
        item.setText(_translate("TitrationWidget", "1"))
        item = self.table_titration.verticalHeaderItem(1)
        item.setText(_translate("TitrationWidget", "2"))
        item = self.table_titration.horizontalHeaderItem(0)
        item.setText(_translate("TitrationWidget", "Label"))
        item = self.table_titration.horizontalHeaderItem(1)
        item.setText(_translate("TitrationWidget", "Initial"))
        item = self.table_titration.horizontalHeaderItem(2)
        item.setText(_translate("TitrationWidget", "Buret"))
        __sortingEnabled = self.table_titration.isSortingEnabled()
        self.table_titration.setSortingEnabled(False)
        item = self.table_titration.item(0, 0)
        item.setText(_translate("TitrationWidget", "L"))
        item = self.table_titration.item(0, 1)
        item.setText(_translate("TitrationWidget", "1.0"))
        item = self.table_titration.item(0, 2)
        item.setText(_translate("TitrationWidget", "0"))
        item = self.table_titration.item(1, 0)
        item.setText(_translate("TitrationWidget", "H"))
        item = self.table_titration.item(1, 1)
        item.setText(_translate("TitrationWidget", "2.0"))
        item = self.table_titration.item(1, 2)
        item.setText(_translate("TitrationWidget", "-0.1"))
        self.table_titration.setSortingEnabled(__sortingEnabled)
        self.lbl_Vi.setText(_translate("TitrationWidget", "Initial"))
        self.lbl_Vf.setText(_translate("TitrationWidget", "Final"))
        self.lbl_V.setText(_translate("TitrationWidget", "Volume"))
